### ISSUE TITLE
[API] Visit schedule rules support to all workflows

### ISSUE THREAD

**Issue by Rakeshdurvasula-PSL** [avniproject/avni-server#119]
Support
- Executing the rule and returning the result to client

Support
- Save Enrolment with Scheduled Program Encounters
- Save Program Encounter with Scheduled Program Encounters
- Save Registration with Scheduled Encounters
- Save Encounter with Scheduled Encounters

Tech Tasks:
- [x] Code Cleanup(merge the code into master and remove old branches, remove unused code)
- [x] Change the API to take the rule code from API request instead of DB
- [x] Test program encounter -> program encounter visit scheduling
  - [x] Test program encounter -> program encounter saving scheduled visits
  - [x] Test unplanned visit
  - [x] Test planned visit
  - [x] Test default strategy
  - [x] Test "createNew" strategy
- [x] Test enrolment -> program encounter visit scheduling
  - [x] Test enrolment -> program encounter saving scheduled visits
- [x] Add and test encounter -> encounter visit scheduling
  - [x] Add and test encounter -> encounter saving scheduled visits
  - [x] Test unplanned visit
  - [x] Test planned visit
  - [x] Test default overriding strategy
  - [x] Test "createNew" strategy
- [x] Add and test registration -> visit scheduling
  - [x] Add and test registration -> saving scheduled visits

**Comment by hithacker** [comment]
Current Estimate: 7 days
