### ISSUE TITLE
Support rules in form element group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#169]
Add new column form_element_group.rule. 

Add the value to API.

**Comment by vindeolal** [comment]
Doc : https://avni.readme.io/docs/writing-rules#from-element-group-rule

**Comment by nupoorkhandelwal** [comment]
@vindeolal What and how do i exactly need to test in this card?

**Comment by vindeolal** [comment]
@nupoorkhandelwal  On the server side we have added a new column `rule` on `form_element_group` table. So from the webApp when you save/edit a form element group rule then it should get reflected on that column.
