### ISSUE TITLE
API for Relationship types

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#174]
In order to support relationship types, we will have the following 

GET /web/relationshipType (No pagination, get everything)
POST /web/relationshipType (Add this relationship type) - Return successfully if success, or if duplicate. Unvoids if already present and voided
DELETE /web/relationshipType/{id} (void relationship type)

**Comment by swapnil106111** [comment]
@vinayvenu  get api returns error Unable to find org.openchs.domain.individualRelationship.IndividualRelation with id 3.

**Comment by vinayvenu** [comment]
```
Creation of relationship Type
POST /web/relationshipType
{
        "individualAIsToBRelation": {
            "id": 94
        },
        "individualBIsToARelation": {
            "id": 90
        }
}


```
