### ISSUE TITLE
Bugbash issues

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#186]
Look at the following issues on the bugbash sheet - https://docs.google.com/spreadsheets/d/1ycRyvs12VwhN2zmeiSMGam5861x87a22P_DUPxt1g1o/edit#gid=831593043

- On import of .docx file, error thrown but is shown technical, please see screenshot
- An irrelevant csv file got uploaded and shows 12 rows completed, please see screenshot

**Comment by 1t5j0y** [comment]
Friendly error message added if non csv file is used for csv uploads.

Second issue about the irrelevant csv has not been fixed as the fields in the 'irrelevant' csv are considered as valid new location levels and imported successfully into the database.

[irrelevant csv](https://app.zenhub.com/files/64591222/9c75ddee-1922-4860-a25c-bdfb6a32b233/download)
