### ISSUE TITLE
Creating catchment from admin without type gives an error

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#192]
Creating catchment from admin without type gives an error.
The type field on catchment is not used anywhere so we will just remove the field from the UI and backend entity.

To test this: create a catchment from admin UI or modify an existing catchment. It should not display type field and it should not result in any error.

**Comment by garimadosar5** [comment]
QA Notes - 
- @hithacker  The "type" field (Create Catchment) is not removed, but it is non-mandatory now.
