### ISSUE TITLE
APIs for doing CRUD operations on video entity.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#200]

**Comment by garimadosar5** [comment]
QA Notes - 
- If Video is voided from UI. In-App it shows with VOIDED tag.
![Screen Shot 2020-05-26 at 10.45.02 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ffbd738a-2772-4a01-907d-7da3dc301429)

**Comment by vindeolal** [comment]
Fixed on client. APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e9ec4-2020-05-26-17-13-19.apk
