### ISSUE TITLE
System does not send OTP for Reset password.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-server#213]
For both Staging and Production.

Steps to reproduce - 
- Go to login page.
- Click on Forgot password
- It will ask for userid, fill userid.
- Click on Send OTP button.
- OTP will not be received.

**Comment by hithacker** [comment]
SMS are stopped right now due to changed regulations. Have asked them to enable it. More details can be found in https://console.aws.amazon.com/support/home?region=ap-south-1#/case/?displayId=7098106101&language=en. The case is open so waiting for their response.

**Comment by hithacker** [comment]
**Status**
We got the approval from DLT https://www.vilpower.in/ last week. We also got the permanent sender ID approval. Now waiting for approval of message templates.
