### ISSUE TITLE
Search Remaining scope

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#220]
### Motivation
As a user when I search for a concept, and I have specified search scope in search filters admin config, I want it to be searched only in that scope. 

### Acceptance Criteria:
- When the search scope is set to Encounter, search for the concept only in the specified subject type and encounter type.
- When the search scope is set to Program Encounter, search for the concept only in the specified subject type, program, and encounter type.
- When the search scope is set to Program Enrolment, search for the concept only in the specified subject type and program.
- When the search scope is set to Registration, search for the concept only in the specified subject type.

Tasks:
Respect search filters saved in organisation config while performing search via DEA (API used: /web/searchAPI/v2)

**Comment by vindeolal** [comment]
Handling of parameters can be decided based on urgency.
