### ISSUE TITLE
java.lang.NullPointerException in FormController.java:255

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#227]
## Error in avni-server

**java.lang.NullPointerException** in **FormController.java:255**

[View on Bugsnag](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/5f4229e032ead40017e0530b?event_id=5f4287cc005df783dd540000&i=gh&m=ci)

## Stacktrace

    FormController.java:255 - org.openchs.web.FormController.export

[View full stacktrace](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/5f4229e032ead40017e0530b?event_id=5f4287cc005df783dd540000&i=gh&m=ci)

*Created by Avni via Bugsnag*

**Fix**
Put null checks on this line for objects that could be null. And make the concept uuid param this API takes not nullable(return HTTP error if concept uuid passed is null or empty or not found)

**Comment by vinayvenu** [comment]
Bugsnag expired.
