### ISSUE TITLE
Slow feedback on export screen after submitting the job

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#234]
The default spring batch job status API is slow and takes time to return the response. This creates a bad user experience as the user doesn't get a quick feedback after submitting the job.
We have already changed the API for data upload, the same API should be used for export jobs also.
Also if it still takes time we should show at least queued to the user first and then 'started' when the job actually starts. The 'Queued' should appear immediately after pressing the Generate export

**Comment by garimadosar5** [comment]
QA Notes - 
- It took 10 secs to show first status.

**Comment by vindeolal** [comment]
Moving it to QA ready. We need to test data export.
