### ISSUE TITLE
Auto view generation changes

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#236]
- Right now view generation fails if org name, subject type name, program name, or encounter type name have any special character in their names other than _.
- View names get truncated if it exceeds 63 chars, for such scenarios use the below policy for the view name,
```
6 characters for the subject type
6 characters for the program name
20 characters for enc type
```
Also instead of org name take username_prefix to start the view name.
- Normalize the view definition, i.e instead of adding all the columns from parent entities just add the id column used for the join.

**Comment by garimadosar5** [comment]
QA Notes - 
- some name are not complete. 
e. g. - unicef_preconception_nashik_indivi_precon_preconception_outcom_
unicef_preconception_nashik_indivi_precon_monthly_monitoring_c_
User - (admin@unicef/password)

**Comment by vindeolal** [comment]
@garimadosar5 names start to get trimmed as per the mentioned policy when it exceeds 63 characters. In the case of preconception org name it very big and there was no username suffix(added now). Now it should be fine. (you'll need yo delete the old views first before creating new ones because names will be different)
