### ISSUE TITLE
API to return the roles for a group subject

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#244]
### GET API to get roles for a group subject: 
URL: /web/groupSubject/{id}/roles

Response:
```
[
  {
    "id",
"uuid",
"memberSubjectTypeId",
"role",
"isPrimary",
"maximumNumberOfMembers",
"minimumNumberOfMembers"
  }
]
```

### POST API to add/remove/edit the member to a group
URL:  /web/groupSubjects
Request:
```
{
"groupSubjectUUID",
"memberSubjectUUID",
"groupRoleUUID",
"membershipStartDate",
"membershipEndDate",
"relationshipTypeUUID",
"individualAUUID",
"individualBUUID",
"enterDateTime",
"exitDateTime",
"exitObservations"
}
``
It should give an error when max number limit of members for this role is reached.

**Comment by 1t5j0y** [comment]
Second API not required since there are existing APIs to add a subject to a group and add relation between subjects which can be reused.

**Comment by 1t5j0y** [comment]
Endpoints for testing:

/web/groupSubjects/<groupId>/roles
