### ISSUE TITLE
Facility user missing in Groups

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-server#249]
### Motivation
Facility users are not able to sync. This is because they are not added to the everyone group by default.
The user is also not available in the dropdown.
As far as user groups and permissions are concerned the behaviour for facility user should be same as the catchment user.

### Acceptance Criteria
1. Create a facility user. Actual : The user is not added to the everyone group. Expected : By default the user should be added to the Everyone group
2. Go to another group -> Search for facility user in dropdown. Actual : The user is not available. Expected : The user should be available in the dropdown to be added to the group.

**Comment by 1t5j0y** [comment]
@arjunk @nupoorkhandelwal Unable to simulate the second issue mentioned. The facility user is available in the user dropdown to be added to the Everyone group as well as other groups. Could you share some more details of the facility user and environment where you observed this behaviour?

**Comment by 1t5j0y** [comment]
Second issue occurred for users mapped to facilities. This was causing a recursive API response of user containing facility containing users... which was breaking the UI on the user groups screens.
