### ISSUE TITLE
Make all the Impl specific S3 bucket private

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-server#250]
- All the buckets where implementations specific data is stored.

- Platform related buckets should not be made private.

**Comment by vinayvenu** [comment]
The following policy has been removed
{
    "Version": "2012-10-17",
    "Id": "Policy1578906566588",
    "Statement": [
        {
            "Sid": "Stmt1578906480802",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::prod-user-media/hasiru/*",
                "arn:aws:s3:::prod-user-media/dam_desilting/*",
                "arn:aws:s3:::prod-user-media/shelter/*",
                "arn:aws:s3:::prod-user-media/hd_ka/*",
                "arn:aws:s3:::prod-user-media/unicef_moha/*",
                "arn:aws:s3:::prod-user-media/mdsr_cg/*"
            ]
        }
    ]
}


uat-user-media
{
    "Version": "2012-10-17",
    "Id": "Policy1572867636021",
    "Statement": [
        {
            "Sid": "Stmt1572867628342",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::uat-user-media/hasiru/*"
        }
    ]
}

staging-user-media
{
    "Version": "2012-10-17",
    "Id": "Policy1572867981074",
    "Statement": [
        {
            "Sid": "Stmt1572867974253",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::staging-user-media/dam_desilting/*",
                "arn:aws:s3:::staging-user-media/hasiru/*",
                "arn:aws:s3:::staging-user-media/yenepoya/*",
                "arn:aws:s3:::staging-user-media/bborg/*",
                "arn:aws:s3:::staging-user-media/Shelter/*"
            ]
        }
    ]
}

**Comment by vinayvenu** [comment]
### Verification steps

1. Go to a report. eg: DDM baseline survey 
2. Ensure that the link to the report comes in blank
3. Try going to the mobile app for one of the organisations that have a media upload mechanism. 
4. Ensure that sync works fine, and the file is created in S3.

**Comment by garimadosar5** [comment]
QA Notes - 
- Cannot see a bucket for MDSR-moha on prod.
-
