### ISSUE TITLE
Fix sync performance for sewa rural

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#251]
https://avni.freshdesk.com/a/tickets/799

### Dev notes:
**Fix details**: Fixing the main query run during the sync by filtering by id instead of UUID. For example, we were getting the program UUID from the client and on the server, we were filtering program enrolments by program UUID. That was causing the query to be very slow. Now we will still be getting program UUID from the client but on the server, we will get an id for that program and filter by the id. Filtering by the id is way faster.
**Dev testing**: Tested it by taking the new query and running it in a production database with the same parameters as the old query.

### Testing
- Since the fix for this touches all sync APIs, we should do make sure that sync is working(from scratch, and partial). You may not really be able to test the performance improvement. We just need to make sure that this is not breaking anything.

**Comment by garimadosar5** [comment]
QA Notes - 
- sync is failing when I am syncing with the data. 
after 77% it gives error "syncTimeoutError".
User - sr-staging/password

**Comment by hithacker** [comment]
@garimadosar5 I am able to sync now. It was because the staging server was under load at that time. I rechecked again to make sure there is no other issue.

**Comment by garimadosar5** [comment]
For me it is failing again with this error.
![Screen Shot 2020-10-22 at 8.33.09 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/195ccdbc-59d3-4f37-9ec4-f4ae25dc6757)

**Comment by hithacker** [comment]
@garimadosar5 Did you try it multiple times?

**Comment by hithacker** [comment]
It seems to be breaking on Garima's machine around 76% 

Below is the server log during that time:
2020-10-23 05:44:20.268  INFO 15957 --- [http-nio-8021-exec-10] o.o.f.security.AuthenticationFilter      : GET /programEncounter?programEncounterTypeUuid=221cbc98-6676-4035-8e6c-59f807f8f06b&lastModifiedDateTime=2019-04-18T05:23:29.990Z&size=100&page=0 HTTP 200. Time Taken: 268 ms
2020-10-23 05:44:20.269  INFO 15957 --- [http-nio-8021-exec-10] o.o.f.security.AuthenticationFilter      : Processed GET /programEncounter?programEncounterTypeUuid=221cbc98-6676-4035-8e6c-59f807f8f06b&lastModifiedDateTime=2019-04-18T05:23:29.990Z&size=100&page=0 User: sr-staging, Organisation: Sewa Rural Old

It repeatedly stops after this same request
