### ISSUE TITLE
Set / Reset user's password from admin app

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#254]
As an org admin, I should be able to reset any users password from the admin app. Right now when users don't log-in for the first time, their temporary password expires, and then we need to reset their password using AWS CLI.  We use the below command to permanently reset their password to password.
`aws cognito-idp admin-set-user-password --user-pool-id $OPENCHS_PROD_USER_POOL_ID --username USER_NAME --password password --permanent`

**Acceptance criteria**
- API that will reset the user's password to "password".
- Button on the admin app which will call this API for a user.

**Tech approach**
- API for java SDK
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cognitoidp/AWSCognitoIdentityProvider.html#adminSetUserPassword-com.amazonaws.services.cognitoidp.model.AdminSetUserPasswordRequest-

**Comment by vindeolal** [comment]
Users should be able to set the permanent custom passwords while user creation.

**Comment by garimadosar5** [comment]
**Test Cases -** 
- Create new user with temporary password.
- Create new user with temporary password and check forgot password flow.
- Create a new user with custom password flow.
- Create a new user with custom password and then check the forgot password flow.
- Test reset password for existing users.
- Test reset password for the new user.

**Comment by garimadosar5** [comment]
QA Notes - 
- Created a new user with custom password flow. Now I cannot see reset password option.
![Screenshot from 2021-08-24 13-53-53.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/77698a59-35e2-4366-9e76-8ab561e87e6b)
