### ISSUE TITLE
Replace the recursive virtual_catchment_address_mapping_table view with flat view

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#257]
Tech tasks:
~ - Write the following triggers ~
~   - When you add a location to the catchment (insert on catchment_address_mapping) ~ 
 ~    - Then the location and it’s all children(recursively) should get added to RCAM ~ 
 ~  - When you add a new location with a parent (insert on address_level) ~ 
  ~   - Check if either of its parents has entries in CAM. if so add the new location to RCAM against those catchments. ~ 
  ~ - When you update the parent of a location (update on address_level) ~ 
  ~   - Remove entries against old parents from RCAM. Check if either of its new parents has entries in CAM. if so add the location to RCAM against those catchments.  ~ 

 ~ - Decide a proper name ~

- Replace the view definition so that view is no longer recursive and performs better than the older view.

**Testing**
- Check if all the components are working fine. DEA, Reports, and Field app sync.
- Check with the organizations that used to time out on sync. This should not happen after this change.
- Check for organizations having different address hierarchies.

**Comment by vindeolal** [comment]
- Checked sync for below organizations
- JNPCT
- Sewa Rural
- IHMP
- Yenepoya

- Checked DEA, admin app, and app designer for SR and IHMP.
