### ISSUE TITLE
API for sending and verifying OTP

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#264]
## Context

As part of this, we will create a wrapper to msg91 APIs for OTP sending and verification so that we can keep the secrets of the API within our server. 

## API signature
```
POST /otp/send
{
	number: "+919333829383"
}

Response: 200

POST /otp/resend
{
	number: "+919333829383"
}

Response: 200

POST /otp/verify
{
	number: "+919333829383",
	otp: "1234"
}

Response: 
{
	verified: true/false,
	error: 'Error message'
}
```

## Msg91 API Documentation
https://docs.msg91.com/collection

## Tech Tasks
- Signup for msg91 (for test purposes)
- Set up templates
- Setup table msg91_config to store msg91 details (with details - authKey, phoneVerificationOtpTemplate and phoneVerificationOtpLength)
- Set up APIs

## Other Details
- It is assumed that every customer will have their own account on msg91 to send messages. These will be stored in our database.  
- Expiry set to 10 minutes
- Errors are sent back to device if they require human action. Others (such as invalid key) are thrown as error. 
- Default 4 digit (1234) PIN will be a valid PIN in dev mode. 

## Error map
This details out what we should do for every error coming out of the msg91 api. 

### SendOTP
```
otp_not_found_and_placeholder_not_found_in_message - Throw error
Message don't contains otp - Throw error
invalid_otp_length - Send error to client
invalid_otp_expiry - Throw error
Some Parameter are missing : mobiles/group_id - Send error to client
otp_expiry_out_of_limit - Throw error
OTP should be numeric - Send error to client
Otp length should be in between 4-10 - Send error to client
OTP in message does not match otp field value - Send error to client
207 - Throw
302 - Throw
303 - Throw
304 - Throw
418 - Throw
```

### Resend OTP
```
retry send successfully - 200
Invalid authkey - Throw
Mobile number empty or not numeric - Send error to client
No OTP request found to retryotp - Send error to client
OTP request invalid - Throw
OTP expired - Send error to client
OTP retry count maxed out - Send error to client
```

### Verify OTP
```
OTP verified success: 200
Invalid authkey - Throw
Otp empty or not numeric - Send error to client
Mobile no. empty or not numeric - Send error to client
Mobile no. not found - Send error to client
OTP request invalid - Send error to client
Mobile no. already verified - Send error to client
OTP expired - Send error to client
OTP not match - Send error to client
Max limit reached for this otp verification - Send error to client
```

**Comment by 1t5j0y** [comment]
- [ ] Msg91 signup, setup
- [ ] Send API
- [ ] Resend API
- [ ] Verify API
- [ ] Msg91 API integration and error handling
- [ ] Dev mode handling
- [ ] ~Template handling~

**Comment by 1t5j0y** [comment]
Staging endpoints:
1. `POST https://staging.avniproject.org/web/msg91Config/`
```
{
	"authKey": "<insertAuthKeyValueHere>",
	"otpSmsTemplateId": "<otpTemplateId>",
	"otpLength": 4
}
```
2. `GET https://staging.avniproject.org/web/msg91Config/`
3. `POST https://staging.avniproject.org/phoneNumberVerification/otp/send`
```
{
	"phoneNumber": "<10 digit phone number>"
}
```
4. `POST https://staging.avniproject.org/phoneNumberVerification/otp/resend`
```
{
	"phoneNumber": "<10 digit phone number>"
}
```
5. `POST https://staging.avniproject.org/phoneNumberVerification/otp/verify`
```
{
	"phoneNumber": "<10 digit phone number>",
	"otp": "<otpreceived>"
}
```
