### ISSUE TITLE
[Webapp]Longitudinal export bugs

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-server#266]
- [x] In the registration report, complete address hierarchy is missing.
- [ ]

**Comment by vindeolal** [comment]
All the address level types will show up in the registration information.

Testing scenarios
- Test with single address hierarchy.
- Test with the multiple address hierarchy. like IHMP(rural, urban).

**Comment by arjunk** [comment]
@vindeolal  Taka Village is part of Taka Subcentre but still the subcentre is showing up empty
![image.png](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/55079c11-6df8-459d-9fdf-0d0e1484e28a)

There is one redundant column showing ind.area. Do we still need to show it?

**Comment by vindeolal** [comment]
- Removed the ind.area column.
- There is a problem with the metadata. There are two subcenter types, out of which one is voided and Taka village is referring to voided type that's why it is not showing.
```
select *
from address_level al
         join address_level_type alt on al.type_id = alt.id
where title = 'Taka'
  and alt.name = 'Subcenter'
  and not alt.is_voided
```
