### ISSUE TITLE
[JSS][Phulwari][Report] Consolidated Monthly Consumption Report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-server#289]
https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit#gid=1304936686&range=17:17

- This report calculates the ration consumption in phulwari based on attendance in Phulwari.
- Filter - Month and year

**Comment by vinayvenu** [comment]
Not sure of context. Closing.
