### ISSUE TITLE
Support for phoneNumber type in the data upload

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-server#299]
**Describe the bug**
Any subject uploaded through CSV having phoneNumber concept, fails to populate the profile at the DEA and in the client as well.
[sample-Subject---Farmer (3).csv](https://github.com/avniproject/avni-webapp/files/6356417/sample-Subject---Farmer.3.csv)

**Comment by vindeolal** [comment]
- We'll mark phone number as unverified.
- It'll have 10 digit validation.whenever it is uploaded from the webapp.
