### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#3]
As a user, I should be able to search beneficiaries using a search term and preferred sorts.

Search - Must search across individual properties (name, observations) and enrolment observations
Sort - On name, gender, date of birth, location
Filter - Enrolled programs, date of birth range (we may introduce this in future depending on requirement)

Search results must be paginated.
Search must take place only for an individual's catchment and not outside.

Testing notes:

```bash
$ cd <workspace>/openchs-client
$ make get-token-staging username=xxxx password=xxxx
## copy the token to /tmp/token
$ curl -o- https://staging.openchs.org/individual/search?size=5\&page=0\&name\=test -H "AUTH-TOKEN: $(cat /tmp/token)"
```

**Comment by sidsamanvay** [comment]
Use Criteria Query Builder to query the data repository
