### ISSUE TITLE
Bulkupload API implementation for users and catchments

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-server#30]
As an API client I should be able to create users through an users import API.
As an API client I should be able to create catchments through same API per user.
As an API client I should be able to assign users to catchments through the same API.

**Locations should already be there in the system.**

Create catchments, users, catchment address mapping, and user catchment mapping.

Input file format: *.csv

| Location with full hierarchy | Catchment Name | Username  | Full Name of User | Email       | Phone         | Language | Track Location |
| ---------------------------- | -------------- | --------- | ----------------- | ----------- | ------------- | -------- | -------------- |
| PHC B, Sub B, Vil B          | A              | user28@ak | user28            | a@email.com | +919876543210 | English  | yes            |
| PHC B, Sub B, Vil C          | A              | user28@ak |                   |             |               |          |                |
| PHC B, Sub C, Vil C          | A              | user28@ak |                   |             |               |          |                |
| PHC B, Sub B, Vil C          | B              | user48@ak | user48            | a@email.com | +919876543210 | English  | yes            |
| PHC B, Sub C, Vil C          | B              | user48@ak |                   |             |               |          |                |
| PHC C, Sub C, Vil C          | B              | user48@ak |                   |             |               |          |                |
| PHC B, Sub C, Vil C          | C              | user68@ak | user68            | a@email.com | +919876543210 | English  | no             |
| PHC C, Sub C, Vil C          | C              | user68@ak |                   |             |               |          |                |

| Language  |
| --------- |
| English   |
| Hindi     |
| Marathi   |
| Gujarati  |
| Bengali   |
| Telugu    |
| Tamil     |
| Kannada   |
| Odia      |
| Malayalam |
| Punjabi   |
| Sanskrit  |
| Urdu      |

**If same user assigned to multiple locations then need not to repeat the userinfo.**

Example file format https://docs.google.com/spreadsheets/d/1klWTBj_cVLuc80sIRPYcpZllxVuea0o4GEO3v5C9o0s/edit#gid=1887642239

**Comment by garimadosar5** [comment]
QA Notes - 
- What to do for Location with full hierarchy, if the user is assigned to multiple locations. 
For eg: Block A <- PHC A <- SC A, SC B, SC C. 
or Block A <- PHC A, PHC B. (i.e user is not assigned to the lowest level of hierarchy).

**Comment by sidsamanvay** [comment]
It is possible to have following associations to user

|Location with full hierarchy|...|
|-|-|
|PHC,SUB,VILLAGE1|...|
|PHC,SUB|...|
|PHC|...|

@garimadosar5 @sidsamanvay

**Comment by sidsamanvay** [comment]
It is possible to have following associations to user

|Location with full hierarchy|...|
|-|-|
|PHC,SUB,VILLAGE1|...|
|PHC,SUB|...|
|PHC|...|

@garimadosar5 @sidsamanvay

**Comment by sidsamanvay** [comment]
> QA Notes 1

both are solved.

@garimadosar5 , @sidsamanvay

**Comment by garimadosar5** [comment]
QA Notes - 
- For User and catchment upload - The file failed to upload because the locations were not there in the system but the status says 'Completed'.
![Screen Shot 2019-11-27 at 1.27.41 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/905766ef-cc1b-40c3-ab36-f75624207b62)

**Comment by sidsamanvay** [comment]
Will show these 2 options:

- completed
- completed with errors

@garimadosar5 @sidsamanvay

**Comment by garimadosar5** [comment]
What is this error?
![Screen Shot 2019-12-03 at 2.42.09 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4193b884-c1e7-49fa-8d0c-d31c8a6fce5c)
