### ISSUE TITLE
Performance issues in sync

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#309]
Sync performance has degraded significantly over time. This ticket is to look at the overall sync mechanism and make necessary changes to improve sync performance.

**Comment by vinayvenu** [comment]
Some changes that can lead to better performance are attached here. Specific outputs
- Modifying virtual_catchment_address_mapping_table can result in a 90% boost in all transactional sync requests
- Moving audit columns to their original tables improve sync performance of concept and conceptAnswer, but degrades performance of transactional sync. 

[https://app.zenhub.com/files/64591222/7d115bac-d4e7-4f7e-8189-358f08bb3cc8/download](https://app.zenhub.com/files/64591222/7d115bac-d4e7-4f7e-8189-358f08bb3cc8/download)

The first change has been committed. Moving of audit has not been pushed to master. There are other options that we can think of. These can be moved to new tickets based on need. 

##### Initial sync
- Increasing page size from 100 to 500 can lead to significant improvements in initial sync times. 

##### Later syncs
- Subject and encounter calls increase with the number of subject types. For non-initial syncs, we can make them much faster by combining multiple subject types. 
- We can look at concept and formElement sync calls in more detail to see why they are performing slow.

**Comment by garimadosar5** [comment]
QA Notes - 
- 63 to 65 in 9 mins
