### ISSUE TITLE
New API to create Locations by uploading CSV file

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-server#32]
We will ask user to upload file with single hierarchy.
File header will have location types. e.g. if hierarchy is PHC -> Subcenter -> Village  then the file header will be PHC, Subcenter, Village.

Examples of different hierarchies:

PHC -> Subcenter -> Village https://docs.google.com/spreadsheets/d/1klWTBj_cVLuc80sIRPYcpZllxVuea0o4GEO3v5C9o0s/edit#gid=35219761

PHC -> Slum
https://docs.google.com/spreadsheets/d/1klWTBj_cVLuc80sIRPYcpZllxVuea0o4GEO3v5C9o0s/edit#gid=487758300

School
https://docs.google.com/spreadsheets/d/1klWTBj_cVLuc80sIRPYcpZllxVuea0o4GEO3v5C9o0s/edit#gid=1811103748

#Testing:
```
cd openchs-client
make get-token-staging username=ck-admin password=xxxx
#cop the token
curl -X POST -F 'file=@/tmp/sampel.csv' 'https://staging.openchs.org/import?type=locations' -H "AUTH-TOKEN: put_the_token_here"
#where the /tmp/sample.csv file is simillar to one of the examples above
#then login as CK-admin on staging webapp and you should see the locations there
```

##### Acceptance Criteria - 
1. It should accept the file only if that is in the format.
2. It should provide the errors if the file failed to upload.  - **Failed**
3. It should give the progress/status of the file upload. 
4. It should take the locations and update the list of locations.
5. If Empty table is uploaded, it shows 0 rows done.

**Comment by sidsamanvay** [comment]
on hold. deprioritized.

**Comment by garimadosar5** [comment]
QA Notes - 
- How it will allow downloading the different hierarchy for different implementations.

**Comment by sidsamanvay** [comment]
> How it will allow downloading the different hierarchy for different implementations.

This card is about upload API. So, not sure what this download is.

@garimadosar5 @sidsamanvay

**Comment by sidsamanvay** [comment]
@garimadosar5, @sidsamanvay 

> QA Notes 1

done

**Comment by garimadosar5** [comment]
QA Notes - 
- If the timeout occurs(page needs to refresh). It says [object Object]. We should put a proper error message there.

**Comment by sidsamanvay** [comment]
> After some idle time any action in webapp results in auth failure.

Fixed it. To test keep the webapp opened for 1-2 hours. It should not throw any error.

> When there is error such as auth failure, browser alerts with '[object object]' message.

Fixed it. Next time when any error happens while uploading a file for `bulkuploads`, error message should show up with proper text.
