### ISSUE TITLE
API to get the list of changed entities

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#326]
This API will receive the entity sync status of the device and will return the list of all the changed entities for each type.

POST API `/syncDetails` with the entity sync status request body 

Response: 
```{
entitiesToSync: [
'concepts',
'forms',
'formElements',
'individuals?subjectTypeUUID=123',
'encounters?encounterTypeUUID=22'
],
now: "currenttime"
}
```

**Comment by vindeolal** [comment]
Moving it back and picking other bugs and priority cards.

**Comment by garimadosar5** [comment]
**Test Scenarios -** 
- Do Fresh sync.
- Sync the app w/o any change in implemnetation.
- Sync with any change in form.
- Sync with addition of subject type and form.
- Sync with a new feature enable like comment, organisation setting etc.
- Sync with change in user group setting.
- Sync with data in app.
- Sync without refreshing home page. (using for JSCS)
