### ISSUE TITLE
Move audit to its own tables

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#332]
Audit being in a different table is causing high sync performance problems for reference tables. If we can move audit to the tables where they came from, sync performance improves. 

### Acceptance criteria
1. All audit values are moved to their own tables
2. The audit table is still kept up to date using triggers (This is necessary because reports could depend on audit tables right now)

### Testing
1. Ensure performance of all reference data queries are faster
2. Complete functional testing on all apps
3. Ensure audit tables are getting filled in, and that tables do not have missing audit ids. 
4. Check hierarchical organisations

**Comment by garimadosar5** [comment]
Test Cases - 
https://docs.google.com/spreadsheets/d/1WL6F2f2wfhvlitb5WEjDop7nKqXDknhHTPfT3q1ylEY/edit#gid=966971642
