### ISSUE TITLE
Multiple issues related to subject migration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#351]
### Scenarios
1. Try creating a new subject. There should be no rows created on subject_migration table
2. Try editing a subject. There should be no rows created on subject_migration table
3. Try changing the address of a subject through the API. There should be a row on the subject_migration table

None of the above scenarios are working right now.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- If address is changed from UI, then it is not creating a row in subject-migration table.
Case - Rahul Wadhawa.
