### ISSUE TITLE
Remove facility based sync

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#364]
Since we'll now support multiple sync strategies, we want to move out of the facility-based sync.

**Tasks**
- Remove Facility and UserFacilityMapping model and its usages.
- At the DB level, we can't drop the facility table because the individual table uses facility_id and it is being used in all our views.  Postgres does not allow to drop column if it's referenced in any other object. (need to discuss this)

**Comment by vinayvenu** [comment]
@vinayvenu As part of this, lets remove the facility_id when we generate views. Add a story to drop the facility_id in this epic, but not in this release.
