### ISSUE TITLE
Drop Facility table

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#370]
Right now facility_id from the individual table is used in all the views and this is the reason why the facility table was not removed in #364. 
As a part of this story, find a way to recreate all the views without the facility_id and then drop the facility table.

**Comment by vinayvenu** [comment]
This is slightly complicated because of the number of views that use the facility_id column.

**Comment by vinayvenu** [comment]
This is not particularly causing trouble, and will not be picked up anytime soon. Closing this card for now.
