### ISSUE TITLE
Avni Webapp - authenticate against keycloak

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#396]
Solution
-----
- Have a generic endpoint on the server which returns all the details about how to authenticate. Deprecate /cognito-details with something generic. We've introduced /idp-details - //Done
-- Show Keycloak and/or Cognito login screen in web-app based on idp-details response (if it is both then the user will choose the IAM server)
-- Implement the Keycloak authentication
-- token re-generation 
-- embedding it in all backend web requests

Acceptance criteria
----------
- [Staging] As a tester, I should be able to authenticate myself for organizations that are using keycloak in the staging environment.
- As a organisation administrator I should be able to create new users.
- As a organisation administrator I should be able to reset password for another user in my organisation.
- As a user, I should be able to authenticate myself.
- As a user, my login sessions should be remembered.
- As a user I should be able to change my password.
- As a user I should be able to logout.

**Comment by vinayvenu** [comment]
Authentication details
We can use simple HTTP API without any library.

curl --location 'http://localhost:8080/realms/Amrit/protocol/openid-connect/token'
--header 'Content-Type: application/x-www-form-urlencoded'
--data-urlencode 'client_id=avni-web-app'
--data-urlencode 'grant_type=password'
--data-urlencode 'password=password'
--data-urlencode 'scope=openid'
--data-urlencode 'username=viveks@calcutta_kids'

more operations related to token are detailed here.

https://www.baeldung.com/postman-keycloak-endpoints

Updated the estimate of the first story from 3->2

**Comment by petmongrels** [comment]
Removing configurations like cognitoInDev. Test cognito, keycloak, both, and none modes.

**Comment by petmongrels** [comment]
There is no existing change password facility in the web app so skipping it.
