### ISSUE TITLE
Avni-client app - authenticate against keycloak

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#397]
Avni-client app - authenticate against keycloak. The configuration to be built into the app when apk is generated. Based on this configuration the forgot password functionality will be disabled.

- Analyse and find plugin for Keycloak auth and token generation
- Fetch token and refresh token on expiry
- Include token in all requests sent to backend server

Acceptance criteria
----------
- As a user, I should be able to authenticate myself in the app.
- As a user I should be able to logout.
- As a user I should be able to logout and login as another user (in staging app uninstall maybe required if the user is switching between cognito and key cloak orgs)
- As a user, my login sessions should be remembered across restarts and even when the app is offline.
- As a user I should be able to change my password.

**Comment by petmongrels** [comment]
Acceptance criteria
----------
- As a user, I should be able to authenticate myself in the app.
- As a user I should be able to logout.
- As a user I should be able to logout and login as another user (in staging app uninstall maybe required if the user is switching between cognito and key cloak orgs)
- As a user, my login sessions should be remembered across restarts and even when the app is offline.
- As a user I should be able to change my password.

**Comment by vinayvenu** [comment]
Authentication details... 

We can use simple HTTP API without any library.

curl --location 'http://localhost:8080/realms/Amrit/protocol/openid-connect/token'
--header 'Content-Type: application/x-www-form-urlencoded'
--data-urlencode 'client_id=avni-web-app'
--data-urlencode 'grant_type=password'
--data-urlencode 'password=password'
--data-urlencode 'scope=openid'
--data-urlencode 'username=viveks@calcutta_kids'

more operations related to token are detailed here.

https://www.baeldung.com/postman-keycloak-endpoints

Updated the estimate of the first story from 3->2

**Comment by 1t5j0y** [comment]
Remaining tasks: handling (get user input) of 'both' idpType configuration and keycloak change password support pending.

**Comment by 1t5j0y** [comment]
'both' handling done.
change password changes in progress. Code review for the bulk of the functionality can be done if bandwidth permits.

**Comment by 1t5j0y** [comment]
change password changes done.
