### ISSUE TITLE
Automate backup of data filesystem for Minio

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#401]
Keycloak and Minio setup using ansible scripts is done.

Pending tasks:
Automate backup of data filesystem for Minio

**Comment by petmongrels** [comment]
no way to test this. moving it back.

**Comment by vinayvenu** [comment]
@petmongrels maybe relatively harder than vagrant, but wouldn't creating a vm using virtualbox work?

**Comment by petmongrels** [comment]
the problem is with virtual box. on mac silicon it is in trial mode. I tried ubuntu box using it yesterday the vm crashed during startup. vagrant is able to communicate fine.

**Comment by himeshr** [comment]
Not Planning to do this. Closing for now, we'll work on it when the need arises.
