### ISSUE TITLE
Performance fix for longitudinal export

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#413]
The core approach is explained here: https://medium.com/predictly-on-tech/spring-data-jpa-batching-using-streams-af456ea611fc but a couple of things need to be managed by us in code.
- closing the stream
- clearing the entity manager either using clear or detach (not sure about whether detach would detach child entities also hence maybe we should use clear after every x number of records)

**Comment by vinayvenu** [comment]
Test cases
1. Run with old and new code for an encounter. Verify that the files are same. (Verified against 7000 encounters)
2. Run exports for subject, group subject, enrolment and encounter. Ensure none of these fail.
