### ISSUE TITLE
Metadata zip upload should contain eligibility configuration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#422]
### Acceptance criteria
- New form types should be migrated through the zip file. 
- New rules should be migrated through the zip file

**Comment by AchalaBelokar** [comment]
1) the offline dashboard  is not working
2) rules are not working

**Comment by petmongrels** [comment]
@AchalaBelokar 
Can you share the zip file you have used?
2. about this, which rule are you referring to? I checked the Program's Manual enrolment eligibility check rule (added in this story) - this was working.

**Comment by AchalaBelokar** [comment]
@petmongrels [https://app.zenhub.com/files/64591222/eee599bc-1f56-4a37-a879-4c78861bfa10/download](https://app.zenhub.com/files/64591222/eee599bc-1f56-4a37-a879-4c78861bfa10/download)

**Comment by petmongrels** [comment]
As discussed.
1. is not an issue
2. the rule is getting exported/imported correctly as we can see from the designer. The rule is not giving results in @testPW because Power's eligibility engine has not provided access to the users with testpw.
