### ISSUE TITLE
Location upload id column is case sensitive

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#423]
Right now, during location upload id column should be "id" and not "Id". This creates a lot of confusion and the chances of error are more. Either we should make it case insensitive or document it clearly so that wrong files are not uploaded.

**Comment by vinayvenu** [comment]
Testing
Try the below csv file on MahaTest organisation. Try changing the location name. 

[https://app.zenhub.com/files/64591222/44a56a03-e52a-46d3-ae0f-31bd0df10e7f/download](https://app.zenhub.com/files/64591222/44a56a03-e52a-46d3-ae0f-31bd0df10e7f/download)
