### ISSUE TITLE
Sync attributes in User is not designed correctly

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#441]
In our current design, a subject type can have two sync attributes - attribute 1 and attribute 2. However, a user has only two sync attributes even though multiple subject types can be configured for a user. This can cause issues configuring two subject types to use attribute based sync (unless both have the same sync attributes, and the values for each attribute are the same for a user). 

### Acceptance criteria
- When creating/editing a user, each subject type that has a sync attribute based sync is shown (on the webapp)
- Sync works correctly based on sync attribute set for a subject type
- Reset sync works for specific subject types that it is configured for

**Comment by AchalaBelokar** [comment]
This option is only shown for goonj user
