### ISSUE TITLE
Make external-api.yml file get auto-updated on swaggerhub

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#447]
Make external-api.yml file get auto-updated on swaggerhub

**Comment by himeshr** [comment]
Couldn't get this to work as it needs read and write access to Avni-project git repo and that seemed a bit too intrusive.

**Comment by vinayvenu** [comment]
@himeshr should we continue to try doing this?

**Comment by himeshr** [comment]
Closing this as the process to auto-update / sync external-api.yml file between github and swaggerhub is not stragightforward.
