### ISSUE TITLE
/syncDetails performance is slow with high number of addresses

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#448]
### To reproduce
Try calling /syncDetails with a catchment of Maharashtra (50k address_levels) for Goonj organisation on staging.

**Comment by himeshr** [comment]
We'll always return true from LocationMappingRepository.isEntityChangedForCatchment(), as the sync for Locations is quite fast and the query to check for change is extremely slow. So doing the check is counter-productive.
