### ISSUE TITLE
[Bugsnag] Send API url along with the error

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-server#45]
In Bugsnag sometimes we get error messages with no clear cause. We can add Web request details to the error log, so we can guess where could be the problem.

It should have the 'API url called', 'useruuid' and 'username' if known.

Relevant code: `org.openchs.web.ErrorInterceptors`

**Comment by hithacker** [comment]
We haven't found any need for this yet so closing this. Generally we are always able to get this information from stacktrace.
