### ISSUE TITLE
Multiple subject assignment to user

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#454]
The way we have direct assignment today, we can only have one user assigned to a subject. However, we need the ability to assign multiple users to a subject. To achieve this, 

The original problem with assigning subjects to users is the double filter issue during sync. Sync does not work very well if there are discriminatory filters on more than one table (because we cannot index multiple tables). There are two scenarios where this should work
1. Assigning a user to a subject
2. Unassigning a user from a subject

### Notes
- Modeling user assignment as a an array of user_ids in the transactional tables does not work because indexing is only possible using gin indexes, and gin indexes are not used during RLS. Also, it is lousy to get this done right. 
- Adding a user_subject_assignment table to the join does not seem to have a huge performance cost for the data (see plans attached)

### Solution
1. Create a user_subject_assignment table (for multiple assignments)
2. Every time a user_subject_assignment happens, touch all entities for the subject so that sync takes care of getting these entities
3. Sync happens to the user_subject_assignment table. This is used to remove subjects that are now unassigned

### Tech tasks
- Create a user_subject_assignment table (and entity). 
- Use this table for assignment based on direct assignment. Remember to check for only non-voided entries on user_subject_assignment table. 
- Sync **voided** entries in user_subject_assignment to avni-client
- Delete subjects that sync through user_subject_assignment on avni-client (override the save function to perform a delete of the subject as well)
- Ensure user_subject_assignment is removed when restoring database from fast sync
~- When a user is reassigned a subject, then the assignment row is unvoided~

### Testing
- Testing can either happen through sql updates, or through the subject assignment screen that we will build. 
- Ensure testing with fast sync, delete data etc.

**Comment by vindeolal** [comment]
Moved "When a user is reassigned a subject, then the assignment row is unvoided" to https://app.zenhub.com/workspaces/ia-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/793

**Comment by vindeolal** [comment]
APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-1bdc-2022-09-01-11-47-26.apk

**Comment by vindeolal** [comment]
Sync configuration for the group and member subject types should be in sync. Right now we are not implementing this feature on the app designer there's a separate card for this.
We'll monitor this inconsistency using the metabse alert https://reporting.avniproject.org/question/2313-different-sync-configurations-found-for-group-and-member-subject-type
