### ISSUE TITLE
External SQL API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#461]
In this query, we develop a model and an external API to run a sql query and retrieve results through the external API. 

### Acceptance criteria
- Model for sql and its parameters present
- Addition of external API to retrieve data based on result
- Column names are not repeated in the result
- External API documentation updated and marked in this card
- Error messages shown when a sql or its parameter are incorrect

**Comment by vindeolal** [comment]
Documentation: https://avni.readme.io/docs/custom-query-api
