### ISSUE TITLE
Prod issue - App goes down [OutOfMemory] when getting addresses

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#464]
To reproduce 

GET - https://staging.avniproject.org/locations/search/typeId/516

This is caused because when we register a subject, we retrieve all addresses from the server for a particular geography and do client-side filtering. This is hard when we do this for organisations with a high number of address levels. 

### Areas affected
- Registration
- Location type form element

### Possible solutions (lets discuss before starting)
- Try enhancing the AddressLevelsByType component by adding a type to it (requires server side change as well). This limits responses, and asynchronously loads addresses (server side filtering). 
- Use autocomplete

### Finalized solution
 - We'll alter the /search/typeId/{locTypeId} to
      1. return a max of 100 entries
      2. accept an optional String that will be used to apply startsWith filter and return a max of 100 entries

### Testing areas
- Registration
- Location type form element
- Search
- Longitudinal export

Ensure testing on staging happens on Goonj organisation.

**Comment by petmongrels** [comment]
for addresses larger than a particular number we should do autocomplete and load based on search parameters

**Comment by himeshr** [comment]
Screenshots of the 3 screens where the fix was made is attached here-in.
![Screenshot 2022-09-16 at 3.57.27 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/980899c3-cc6e-4297-8294-5a9c0972a121)
