### ISSUE TITLE
Remove /locations/web/getAll

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#467]
This is a potentially dangerous method if there are a lot of locations in the system. 

- Remove /locations/web/getAll from server
- Remove /locations/web/getAll usages in avni-webapp

**Comment by himeshr** [comment]
The code change was to remove a costly api call invoked during app login, whose data was not used in any screen.
So, to test it, you may check the console, network tab on webapp and confirm that there are no calls to "/locations/web/getAll" at any point of time.
![Screenshot 2022-12-26 at 3.56.46 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/c774d084-c194-4fb2-8110-c813cd8d00ad)

**Comment by vinayvenu** [comment]
Closing this card as it has gone live.
