### ISSUE TITLE
Reduce scope of reset_sync for change in sync parameters for a user

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#471]
### Summary
When there are new sync parameters added for a user, only the subject type that is related to that subject are relevant to be reset. More specifically, we do not need to reset reference data when this happens. This is specifically an issue if the reference data is huge. 

This story limits the scope of reset when a reset_sync takes place. 

### Acceptance criteria
- A new field is introduced in reset_sync that provides the purpose of the reset_sync
- Possible reasons for reset_sync include "User Catchment change", "Subject Address Change", "New Sync parameter added for subject", "New Sync Parameter added for User". 
- All inserts to reset_sync provide the right value. 
- This flag is synced to avni-client, where necessary action is taken

**Comment by mahalakshme** [comment]
@vinayvenu why is this card needed when subject_type_id was added in this story: https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/369

**Comment by vinayvenu** [comment]
@mahalakshme  The one piece that is missing is the reference data delete. We don't need to do delete of reference data when doing sync reset.

**Comment by mahalakshme** [comment]
added here: https://github.com/avniproject/avni-client/issues/1269 so closing this
