### ISSUE TITLE
Application Menu should be included in bundle export

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#472]

**Comment by vinayvenu** [comment]
Tested
- Download zip for existing menu item and upload to new org
- Download zip for voided menu item and upload to new org

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-29 at 6.35.08 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/aeddbab5-e0c7-4f93-8e1c-32a41f492ee4)
