### ISSUE TITLE
Voided form mappings should not fail the app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#477]
Currently, when syncing encounters, program encounters and enrolments, we do not look up form mappings that are voided. This is 
because we need the correct mapping that is linked to the entity. 

However, there are situations where a client can request for a form mapping that is already voided. The server currently fails for such a request. This should instead give out an empty response. 

### How to reproduce
- Add an encounter type. Add a form to that encounter type. Void the form mapping, and try to sync. App sync will fail. 

### Affected apis
Sync apis GET of /encounter, /programEncounter and /programEnrolment

### Sample Error stack trace
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/6336e7ece4beff0008fa069e?event_id=6336e7ec009784a9e6930000&i=gi&m=nw

**Comment by himeshr** [comment]
Code changes look good, moved to DevComplete.

**Comment by vinayvenu** [comment]
Deployed to prod (release 3.34.1).
