### ISSUE TITLE
Send message to users

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#487]
### Acceptance criteria
- When scheduling and sending messages, the receiver is chosen based on the receiver_type provided in the message_rule table. 

### Testing notes
- Test for subject, program enrolment, program encounter and encounter workflows
- Test for new and existing user workflows

### Tasks:
- Pick phone no from phone of user instead of observations
- Save receiver as Logged in user instead of the subject.

**Comment by mahalakshme** [comment]
@AchalaBelokar now beneficiary subject type in messagesToGlific should work as expected. The problem was because we were queuing messages for deleted rules as well. Now that is fixed.
