### ISSUE TITLE
[SNCU] cancel observations can't be fetched in offline report cards

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-server#488]
In implementation SNCU, we need to fetch cancel observations to check the visit cancel reason, the following rule prints blank in console, though there are cancelled encounters present.--

let encounters = _.chain(enrolment.getEncounters())
      .filter((enc) => { 
      if(enc.cancelDateTime != null){
      console.log('cancelDateTime',enc.cancelDateTime);
       console.log('cancelObservations',enc.cancelObservations);
       }
      return enc.cancelDateTime != null;})
      .value();

**Comment by vinayvenu** [comment]
Verified with Nupoor and Taqi. This is not an issue. Closing this card.
