### ISSUE TITLE
Sync attribute inconsistencies

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#492]
https://reporting.avniproject.org/question/2114-sync-attributes-inconsistencies

**Comment by himeshr** [comment]
Fixed the sync attributes mismatch in Sakhiapp implmentation by making corrections in address_id value for encounter, program_encounter and program_enrolment, in-addition to individual.![Screenshot 2022-12-05 at 12.12.40 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/a6f6c350-f5b3-4094-88e1-45e01cdca04d)
