### ISSUE TITLE
Fix cache for addresses

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#501]
We have a cache for Addresses in avni-server. This currently has a few issues
1. Aggressive cache eviction
2. Low cache size

- Increase the cache eviction time to around 30 minutes
- Provide cache size in terms of weight instead of number to account for a higher number of cache entries

Test to ensure that the above configuration works fine.

**Comment by himeshr** [comment]
- Increase the cache eviction time to around 10 minutes
- For caching addresses, introduced weighted cache capacity management policy instead of number 
- For non address caching, continuing with usage of number of entries

**Comment by himeshr** [comment]
Following performance tests were carried out on avni-server with 2GB Heap space configured for it:

- Fetch syncDetails for a single user in 10 threads at same time
- Fetch syncDetails for 10 different users randomly a 50 times in 30 seconds
Perform above tests repeatedly one after another around 4-5 times
We did not observe any memory limit exceeding (OOM) errors.

**Comment by himeshr** [comment]
To be tested:
for multiple organizations, validate that,

-  Locations are getting loaded during initial sync
-  Sync completes successfully
-  Data created gets synced back to server

**Comment by AchalaBelokar** [comment]
- [ ] Lahi organisation I created one student  Rana da then I edit the birth date but it is not reflecting on client

**Comment by mahalakshme** [comment]
@AchalaBelokar in LAHI, we sync by direct assignment. Try doing that for the subject to sync. I tested in maha_test organisation where sync happens by location and it worked fine.

**Comment by himeshr** [comment]
@Achala, in continuation to Maha's comment above, in LAHI, we need the subject to adhere to both 
- Catchment constraint
- Direct Assignment constraint
in-order for the subject to be synced to the avni-client android app.
Therefore the testcase which failed for you was a valid one, as the subject doesnot satisfy the Direct Assignment constraint.
I validated this for a new subject, by assigning the subject to test user.
