### ISSUE TITLE
Avni bombards Glific API server with requests resulting in their system crashing

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#507]
### Issue:

Lobo suspects that Avni server for LAHI implementation is spamming Glific api quite a bit.
Because of our request bombardment, their servers went into a spin loop with machine restarts.

He blocked the user by setting thier role to {none}. This could have triggered something on our end, and we stopped sending the requests, aiding their systems recovery.

### Action needed:
We need to investigate on our end about possible scenarios that could have caused this. We suspect some error case scenarios that could be resulting in us bombarding the Glific api server with same erroneous request non-stop.

### Action items
- Add logs in avni-server for every external service call to Glific
- Move job to run once in 5 minutes
- Ignore requests when phone number is not there

**Comment by vinayvenu** [comment]
Comments here - https://github.com/avniproject/avni-server/commit/7fa955496b8910e2a4217284773e7a1a9af869cc

**Comment by petmongrels** [comment]
I will do the QA for it once it is deployed in live servers

**Comment by himeshr** [comment]
@petmongrels backend code is deployed to live server

**Comment by vinayvenu** [comment]
@petmongrels this is deployed, but does not have any organisation who has it set up. What should be done?

**Comment by petmongrels** [comment]
I am not sure what you mean by deployed and not in use.
