### ISSUE TITLE
Server response times degrading (see comments for tasks)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#508]
Given below is the server response times for the past 7 days. Over the past 2 months, response times have been slowly degrading. We need to take a look to understand any quick bottlenecks that we can fix. 

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/1d3d44b9-c93b-4cf6-b16c-c99821b90105)

Notice that over the past 3 months, our response times have been slowly creeping up. There also seems to be a spike in the number of requests, so this might be a need to scale up our infra, but it will be good to be sure what needs to be done.

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/5dd3d04a-47e2-48d4-a523-e511644f6512)

**Comment by 1t5j0y** [comment]
Not seeing any specific points that can be quick fixed and the response time degradation seems to be tied to increased load leading to increased memory (app and db) and cpu (more on db) usage.
Some things we could try before scaling up infra:
1. Change (app) instance type to t3 from t2. t3 has better network capabilities - can see if this helps for the short term.
2. Server is limited to 2GB of memory while the app server has 4GB available. Even with the rule server etc running, server memory usage peak usage has touched only about 80% of available memory and is typically around 60%. We should be able to safely increase the max memory available to the app (2.5-3GB).

**Comment by vinayvenu** [comment]
### Current tasks
1. Change app instance type to t3
2. Increase xmx to 3GB

To be done post 6pm

**Comment by vinayvenu** [comment]
Upgrade complete. Also did a full vacuum on the db (db size went down about 30%). 
Initial results are not so promising. Response times are still in the > 400 ms range. Will wait a couple of days and monitor. Card will remain in progress until then.

**Comment by vinayvenu** [comment]
Additionally, changed volume from gp2 to gp3 (which has a higher baseline IOPS). Critical violations have come down greatly after this change.

**Comment by vinayvenu** [comment]
Closing this card. We will figure out if there are other changes to be made through the performance epic.
