### ISSUE TITLE
Registration sync attribute change does not flow through to other entities

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#509]
When a registration sync attribute changes, the change needs to be persisted across every place where it is saved - individual, encounter, program_enrolment, program_encounter, entity_approval_status. This happens today only on the individual table, and is causing attributes to be different across different tables. 

During /individual save, if there is a change in the sync attribute, all these fields must be modified to ensure that the attributes are in sync. 

During debug found the following issues:
- On edit of individual, highRisk flag is reset due to default decision value set for individualRegistration form
- On create/update of programEnrolment, decision concept is stored as an array instead of single value. Because of this following side-effects were seen:
-- highRisk individual doesnot get synced to qrt users phone
-- On change in high-risk flag from Yes to No, individual is not removed from QRT users phone

**Comment by himeshr** [comment]
Tested out the following scenarios on staging for "apf bundle test" org:
 - Storing correct format syncConceptValue on marking Individual as "HighRisk" during Pregnancy enrolment
 - Updating all related entities on syncing the individual with the correct syncConceptValue
 - HighRisk users are getting synced to QRT user
 - On changing "HighRisk" user from yes to no, the individual got removed from QRT user

**Comment by AchalaBelokar** [comment]
- [ ] When I register hight risk preg in qrt user.it is showing
