### ISSUE TITLE
API to download file once job is complete

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#51]
API to download file from S3 by passing correct fileName.

**Comment by garimadosar5** [comment]
QA Notes - 

Cannot download the data - !
[Screen Shot 2019-12-03 at 3.20.16 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5b663cd7-807e-4aba-8031-ba01689cf4fd)

**Comment by vindeolal** [comment]
@garimadosar5 
Media directory was not set for the organisation, which was giving this error.
I have set the media directory. You can try to regenerate and download the report.
