### ISSUE TITLE
Changes Phase 1 - New sync API without counts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#515]
As part of Changes Phase 1, we will perform some changes before running performance tests

### Acceptance criteria
- Create a new version of the sync APIs for transaction data that do not run the count query

### Not in scope
Changes to avni-client. We will incorporate this once we are clear of performance advantages

**Comment by 1t5j0y** [comment]
Compared performance with and without this change. Test results linked to in the cards below.
[without slice](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-perf/4)
[with slice](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-perf/5)
