### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#520]
### Motivation:
Lets start the year by deleting code. :)
- This will reduce analysis/development overhead when doing stories that impact across all the models like React upgrade or embedded objects.
- Questions raised from implementation team since these unused tables etc., are causing confusions.

### Acceptance criteria:
- Remove ProgramOutcome, ProgramOrganisationConfig, ProgramConfig related dead code. Looks like the associated models VisitScheduleConfig, VisitScheduleInterval also can be deleted
- Also remove Decision in models not in server since that is used
- Also remove ConfigFile and UserDefinedIndividualProperty in models
- For the removed code in models add migration to delete the respective tables.
- Create a dummy method in controller for sync backward compatibility where needed and delete repository, service, controller, sync related code etc., across codebases.(server, model, client, etc.,)
- The corresponding tables doesn't have any information though there are entries in program_organisation_config which seems to be useless.
- Delete checklist_temp and checklist_item_temp tables
- Remove the table dashboard_card_mapping
- Make sure once before deleting the above.

**Comment by mahalakshme** [comment]
@petmongrels I found not everything mentioned in AC were deleted like checklist_temp and checklist_item_temp tables, ConfigFile, Decisions etc.,  If it was intentional, whats the reason?

**Comment by vinayvenu** [comment]
Regression only. Closing
