### ISSUE TITLE
The password set in reset password by org admin, can get logged and exposed

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#522]
**Describe the bug**
The password during the reset password is sent in query param which can get logged on the server.

**To Reproduce**
- reset password from web app as an org admin for another user. check that the new password is being sent via the query params

**Expected behavior**
- The password should be sent via post or put

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [NO] Does the fix require extensive regression testing?
- [NO] Are you mentioning the required scenarios that could be affected?

**Comment by himeshr** [comment]
@AchalaBelokar The issue we observed in staging for Minio org was due to the fact that "Use Keycloak as IDP" was enabled, though you had thought it wasn't.

![Screenshot 2023-04-11 at 3.55.11 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/478bb2f7-acef-463c-8ada-e8a349ae0081)
