### ISSUE TITLE
Numeric decisions returned by rules-server don't reach the webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#526]
Consider the following decision rule

```
"use strict";
({params, imports}) => {
    return {
        encounterDecisions: [{name: "Abc calculated", value: 1.2}]
    }
};
```

Try this on any environment/implementation (assuming there is a numeric concept called "Abc calculated". The decision will not show on the webapp screen (or on the response of POST /web/rules). 

The following rule, however, works (numeric converted to text)

```
"use strict";
({params, imports}) => {
    return {
        encounterDecisions: [{name: "Abc calculated", value: "1.2"}]
    }
};
```

**Comment by himeshr** [comment]
Code changes made in rules-server..
