### ISSUE TITLE
Bugsnag Error

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#528]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/63fca9a96b39bc000808eaf6

https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by himeshr** [comment]
## Sync Details response logged in avni-client: 

DEBUG  [11:19:43:845] [Requests][Debug] POST: https://server.avniproject.org/v2/syncDetails
 INFO  [11:19:43:845] [AuthService][Info] Found token
 DEBUG  [11:19:44:790] [SyncService][Debug] Entities to sync UserInfo,,Encounter,10ee6154-2f64-482a-a092-a62ab4d2b5b7,Encounter,d73ceefd-ffc9-498c-b8d3-578169605c4c,Encounter,63130228-d55b-4ba2-8aa2-d09c74b6fe7c,Encounter,54d92848-60e0-4b01-bff7-b22b434cc807,Encounter,e36cfe15-5963-42b2-95b3-fea314c8b667,Encounter,5d19a049-08fc-4cca-9a90-7c957c4e248a,Comment,561ddbf6-3a6d-4088-a369-514dcfc44f19,CommentThread,561ddbf6-3a6d-4088-a369-514dcfc44f19,Encounter,83ceab25-b72e-456d-9170-c1b16f4b84bb,Encounter,ac75d74b-8228-4373-8e9f-87e5f63e6961,CommentThread,561ddbf6-3a6d-4088-a369-514dcfc44f19,Encounter,ac75d74b-8228-4373-8e9f-87e5f63e6961,Comment,561ddbf6-3a6d-4088-a369-514dcfc44f19,Individual,ad2ab138-b89f-48e1-aa96-f8626221cef3,Encounter,83ceab25-b72e-456d-9170-c1b16f4b84bb,Encounter,42cf60ce-9a46-4468-8718-ac58552d361a,EncounterEntityApprovalStatus,e36cfe15-5963-42b2-95b3-fea314c8b667,EncounterEntityApprovalStatus,ac75d74b-8228-4373-8e9f-87e5f63e6961,SubjectEntityApprovalStatus,a961a36a-4728-4389-9934-a052067ee6a5,EncounterEntityApprovalStatus,10ee6154-2f64-482a-a092-a62ab4d2b5b7,SubjectEntityApprovalStatus,73271784-512d-4435-8dc8-0f102b99d682,SubjectEntityApprovalStatus,ad2ab138-b89f-48e1-aa96-f8626221cef3,EncounterEntityApprovalStatus,63130228-d55b-4ba2-8aa2-d09c74b6fe7c,SubjectEntityApprovalStatus,561ddbf6-3a6d-4088-a369-514dcfc44f19,EncounterEntityApprovalStatus,42cf60ce-9a46-4468-8718-ac58552d361a,EncounterEntityApprovalStatus,83ceab25-b72e-456d-9170-c1b16f4b84bb,EncounterEntityApprovalStatus,d73ceefd-ffc9-498c-b8d3-578169605c4c,EncounterEntityApprovalStatus,54d92848-60e0-4b01-bff7-b22b434cc807,EntityApprovalStatus,
 DEBUG  [11:19:44:895] [Requests][Debug] GET: https://server.avniproject.org/v2/me?lastModifiedDateTime=2023-04-17T06:05:03.405Z&now=2023-04-17T06:04:55.712Z&size=100&page=0

**Comment by himeshr** [comment]
The issue was caused die to avni-client sending all previously sync entityTypes to be included in the syncDetails response, which over-rode the disabling of sync for Encounter/ProgEncounter/ProgEnrolment, once their FormMappings have been voided.
To fix this, we'll now remove the Encounter/ProgEncounter/ProgEnrolment entries from syncDetails response, if they are not present in allSyncableItems generated based on FormMappings.isVoided status.

**Comment by petmongrels** [comment]
Need to understand this change and EntityApprovalStatus. We need very detailed inline documentation for these as from the code it is not obvious why it is there. We can do that after the discussion

**Comment by himeshr** [comment]
@petmongrels Added inline comment about the purpose of this code.
