### ISSUE TITLE
In Message rule/schedule rule of program encounter, program enrolment not accessible

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#529]
Steps to reproduce:
- Go to any org
- Go to any program encounter
- add a message rule/schedule rule - that accesses params.entity.programEnrolment - this returns null, but should have the details of the object.

Suggestions to fix:
- In RuleServiceEntityContractBuilder class, using constructProgramEncounterContract in toContract method instead of constructProgramEncounterContractWrapper could fix the issue.
- Check in code for other entities - Subject, ProgramEnrolment and Encounter as well, if all the related entities accessible in other rules are accessible in message rule and schedule rule.

**Comment by sachsk** [comment]
As discussed with himesh we are not passing the enrolment to the individual.
There are already card for this
https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/711

moving to hold

**Comment by petmongrels** [comment]
- what is the need for this check encounter.getProgramEnrolment().getUuid() != null
- i think instead of overloading the method name we can call it programEnrolmentWrapperForMessageSchedule (as it is not an override since always true is passed)

**Comment by sachsk** [comment]
@petmongrels did the changes as per your suggestions

**Comment by mahalakshme** [comment]
working as expected. discussed with Achala and Sachin
