### ISSUE TITLE
Location details need to be added to longitudinal export

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-server#546]
### Acceptance criteria
- New fields for location on registration, encounter, program enrolment and program encounter are added to the longitudinal export
- The fields should be available on the new longitudinal export
- The fields should be configurable on the json document for new longitudinal export
- Necessary documentation changes are made in https://avni.readme.io/docs/new-longitudinal-export

**Comment by petmongrels** [comment]
Following JSON gives error on prerelease for APFOdisha saying the field is not recognised.

{
  "individual": {
    "uuid": "ec69af69-8fd2-40b3-b429-025504c18a01",
    "fields": [
      "id",
      "uuid",
      "registrationLocation"
    ],
    "filters": {
      "addressLevelIds": [],
      "date": {
        "from": "2020-01-12",
        "to": "2023-07-04"
      }
    },
    "encounters": [
    ],
    "groups": [
    ],
    "programs": [
      {
        "uuid": "5538d0f1-194c-4055-9311-dcc0239fe1ce",
        "fields": [
          "id",
          "uuid",
          "enrolmentLocation"
        ],
        "encounters": [
          {
            "uuid": "5c68b335-0456-4111-ae77-4697cb61cd56",
            "fields": [
              "id",
              "uuid",
              "name",
              "encounterLocation"
            ],
            "filters": {
              "includeVoided": true
            }
          }
        ]
      }
    ]
  },
  "timezone": "Asia/Calcutta"
}

**Comment by 1t5j0y** [comment]
Changes for this were in master. Have cherry picked it into 3.39 after checking with Vinay.
