### ISSUE TITLE
External API must support media urls

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#552]
### Context

When posting from an external API, image urls do not get special treatment. There is no external API to add media directly to Avni either. 

### Acceptance criteria
- As an external API user, I should be able to add an image when I create or edit an entity (Subject, Program Enrolment, ProgramEnconter, Encounter or Task). 
- The media is moved from the source location (provided in the observation as a url) to the Avni media server (either S3 or Minio)
- Upload should work for all media concepts (Image, Video)
- Upload should work for both single and multiple media uploaded as part of the same concept
- If the form element allows multiple images, then the observation is stored as an array even if only one image provided
- POST Response should contain this new Avni URL

### Tech notes
- Entity save is a separate transaction (starts after media save is complete)

### Assumptions
- Every media url is considered distinct. There is no need to verify if media sent in two different requests is the same. For example, if "http://abc/image.jpeg" is provided in two different posts, it is uploaded twice to the media server without verifying if they are actually the same
- If upload of a media image url fails, the entire entity save fails. We will not do partial save of an entity
- 

### Testing notes:
- images like say https://cdn.pixabay.com/photo/2011/09/27/18/52/bird-9950_1280.jpg, from pixabay website not getting downloaded(403 forbidden error) - this was bcoz user-agent header was not getting set. Since this is not a valid usecase, this is not a bug.
- Handling of validations of media concepts moved to separate card since not working even using field app
- Test cases:
        - For creating subject - singleselect - image - s3
	- Program enc. - multiselect - image - s3
	- Program enc - video - single select - s3
	- Validations - added separate card 
	- Task - image - s3
	- Minio - individual registration - image
	- Audio - program enrolment - minio
	- With media service - not tested - should work
	- If upload of a media image url fails, the entire entity save fails. We will not do partial save of an entity
	- If the URL provides is from the Avni media server then Avni will simply update the observation but not try to move the media file.
	- PUT request - image in programEnrolment Exit observation

**Comment by petmongrels** [comment]
update API documentation

**Comment by vinayvenu** [comment]
1. TaskApiController - We will need to do this for task.metadata as well.

**Comment by petmongrels** [comment]
Can task metadata have a media url? how is it will used?

**Comment by vinayvenu** [comment]
Task metadata is treated similar to all Observations in Avni. However, we do not have any mechanism to show images in task metadata on the UI anywhere. 

We can ignore it then. Moving the card.

**Comment by mahalakshme** [comment]
POST to https://staging.avniproject.org/api/subject using mahatest project auth-token shows error:

`{
  "External ID": "",
  "Subject type": "beneficiary",
  "Address": "Dummy2",
  "Date of birth": "2022-11-09",
  "Gender": "Female",
  "Registration date": "2022-11-09",
  "Registration location": {
    "X": 19.1253108,
    "Y": 74.7364501
  },
 "observations": {"photo": "https://cdn.pixabay.com/photo/2011/09/27/18/52/bird-9950_1280.jpg"},
  "First name": "photo",
  "Middle name": "",
  "Last name": "test",
  "Profile picture": "",
  "Voided": false
}`
