### ISSUE TITLE
Documentation for Longitudinal export

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#554]
I have created an Initial draft of the "New Longitudinal export" reference documentation, which is available [here](https://docs.google.com/document/d/1zwgr0sEJNR0CxeERZjxvHax0B2ll6oFTg1aVDIZYXBc/edit?usp=sharing)

**Comment by himeshr** [comment]
I have created an Initial draft of the "New Longitudinal export" reference documentation, which is available [here](https://docs.google.com/document/d/1zwgr0sEJNR0CxeERZjxvHax0B2ll6oFTg1aVDIZYXBc/edit?usp=sharing)

**Comment by himeshr** [comment]
@arjunk Document available on Avni readme at https://avni.readme.io/docs/new-longitudinal-export
