### ISSUE TITLE
Subject type is getting created twice when uploading the bundle, due to which app designer cannot be accessed and the app designer page keeps loading for ever.

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/avni-server#560]
Steps to reproduce the issue are:
- Download and upload a bundle to an org hat already contains certain subject type (say individual).
- Once the upload is successful/partially successful, you can try to refresh App Designer or check DB, the app designer will keep loading and in the DB we could find two different active individual subject types (though they are identical).

Attaching the bundle file which i uploaded as well,
[https://app.zenhub.com/files/64591222/4a450f5c-734b-42dd-85fa-617e118f9192/download](https://app.zenhub.com/files/64591222/4a450f5c-734b-42dd-85fa-617e118f9192/download)

apf odisha prod to apf odisha prerelease

Steps to re-create:
1. Create org A
2. Create org B
3. Create Subject type in A
4. Export A as bundle1
5. Import bundle1 to B (<- import 1)
6. Add a sync concept to subjectype in A
7. Export A as bundle2
8. Import bundle2 to B (<- import 2)
9. Observer errors in import 2

**Comment by AchalaBelokar** [comment]
- I checked in prod it is working fine with me

- the org name is bundle upload 1 and bundle upload2

**Comment by vinayvenu** [comment]
Achala, please close this issue if appropriate
