### ISSUE TITLE
Entity Approval Status not getting saved from the webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#563]
Acceptance Criteria:

1. When approval feature is enabled, for any newly created
    1. Subject/Individual
    2. Encounter, ProgramEncounter
    3. Enrolment, ~Checklist~ 
  make sure that a pending approval is inserted.
2. During edits, always set status to Pending. 

Based on #824 : ApprovalStatus workflow for Checklist Item is broken. No code changes were done for this workflow since number of entry points are many and it is not straightforward to decide which points warrant approval . Currently its not possible to enable approval for checklist form.

Test cases:
- Subject registration with approval enabled and disabled-done
- General Encounter creation and cancellation with approval enabled and disabled-done
- Program encounter creation with approval enabled-done
- Program enrolment with approval enabled-done

Tasks:
- [x] Remove code from  3.39
- [x] Rebase and work on master as part of 4.0.0
- [x] Handle edit of Individual ---> Record created on server and synced to client
- [x] Handle edit of Encounter ---> Record created on server and synced to client 
- [x] Handle Encounter cancellation ---> Record created on server and synced to client
- [x] Handle creation and edit of ProgramEnrolment ---> Record created on server and synced to client 
- [x] Handle ProgramEnrolment exit ---> Record created on server and synced to client 
- [x] Handle edit of ProgramEncounter ---> Record created on server and synced to client 
- [x] Handle ProgramEncounter cancellation ---> Record created on server and synced to client

**Comment by ashusvnath** [comment]
Inputs:

@vinayvenu says the issue is with Avni-server and not Avni-webapp

**Comment by ashusvnath** [comment]
Based on discussion with @vinayvenu , creating a `/web/`end-point for web-app use would preserve all the customisations needed for server-client interactions with existing end-points while allowing for behavioural similarity of web-app with client.

**Comment by ashusvnath** [comment]
@mahalakshme : Code changes on f/563_create_approvals_for_web_app_dataentry in `avni-server`  repo.

**Comment by ashusvnath** [comment]
@mahalakshme : Web-app code changes in f/563_approvals_for_webapp_data in avni-webapp

**Comment by mahalakshme** [comment]
changes in webapp and server

**Comment by mahalakshme** [comment]
changes in webapp and server

**Comment by sachsk** [comment]
QA notes:

- On edit, the entity should go in the pending state this workflow is not working on DEA.

**Comment by vinayvenu** [comment]
Move code to master for 4.0.0 release.

**Comment by ashusvnath** [comment]
Reverted code from 3.39 on avni-webapp and avni-server.

Created branche to track changes for 563 on master for avni-server
