### ISSUE TITLE
Unable to create super admin user because of null pointer exception

### ISSUE THREAD

**Issue by ashusvnath** [avniproject/avni-server#566]
## Steps to reproduce error:

1. Log into web app as super admin
2. Click on Users on the left
3. Click "+ Create User" button on the top right
4. Choose the option to make user an admin (use default account), don't associate user with any organization
5. Fill in details and click save.
6. A error message is shown 

Checking server side logs reveals a `null` pointer exception  in `UsersController` because of a missing `organization`. Handle this case appropriately

## Acceptance criteria:
- Being able to create super admin in cognito and keycloak
- Documentation for creating super admin in keycloak is there in [readme](https://avni.readme.io/docs/on-premise-setup-of-avni-without-cloud-services#setup-super-admin-user)

**Comment by petmongrels** [comment]
- In UI also admin users tab in web app will now only show super admins and not org admins based on deprecated column.
- In environments that support both idp types, there is no way to know where to create super admins, so it will always create in cognito. in environments with only keycloak it would create super admin in keycloak (we don't have env like that though for general testing).
