### ISSUE TITLE
Add group membership when creating users using csv import

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#573]
### Motivation
When creating users through csv import, we currently do not have the ability to mark the groups that they are part of. This is causing errors in sync, additional work etc. As part of this story, we will be providing the ability to specify user groups in the csv file

### Acceptance criteria
- Column name: "User Groups"
- Values: Pipe separated names of User Groups (We can talk which separator makes sense during development)
- Validation to ensure all group names are valid
- Works on re-upload of "Users and Catchments"
- "User Groups" column is not mandatory
- If User Groups column is not present, then no changes are done to the group membership
- ~The value in User Groups is exactly replicated (if the user exists with a different set of groups, then they are removed and the new one added)~

**Comment by ashusvnath** [comment]
Dev tested scenarios -> Result
1. CSV with no "User Groups" column -> New user gets added to "Everyone" group
2. CSV with wrong name in "User Groups" column -> Error in upload
3. CSV with empty name in "User Groups" column -> Error in upload
4. CSV with correct groups including "Everyone" group (eg "GMP Child|Everyone" in calcutta_kids) -> User is added to both groups
5. CSV with correct groups but no "Everyone" group  (eg "GMP Child" in calcutta_kids)-> User is added to specified groups and "Everyone" group

**Comment by AchalaBelokar** [comment]
1. I uploaded wrong group name user is not created but I got msg on my mobile no.

![Image](https://github.com/avniproject/avni-server/assets/104890488/14ad3537-5c67-40c6-ae8b-7055a22e44ed)



[errors-calcutta_kids-usersAndCatchments.csv](https://github.com/avniproject/avni-server/files/12160271/errors-calcutta_kids-usersAndCatchments.csv)

**Comment by ashusvnath** [comment]
Moved IDP user creation to after group membership creation to ensure transactional consistency.

**Comment by AchalaBelokar** [comment]
1. Need to test where sync attributes are present.
