### ISSUE TITLE
Add audit fields to sync telemetry table

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#578]

**Comment by AchalaBelokar** [comment]
1. Not able to see this field I deployed latest server on staging

**Comment by vinayvenu** [comment]
<img width="465" alt="image" src="https://github.com/avniproject/avni-server/assets/344222/7e7bbb31-32ca-4626-b07d-3574c59ea223">

**Comment by AchalaBelokar** [comment]
This all is coming and the table is updating after sync is happening.
