### ISSUE TITLE
Create Admin group when creating an organisation

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#579]
### Acceptance criteria
- [x] When an organisation is created from the screen, an "Admin" group is created by default
- [x] The "Admin" group has All privileges turned on by default (cannot be revoked, which is handled in a different story)

**Comment by himeshr** [comment]
Screenshot:



![Image](https://github.com/avniproject/avni-server/assets/72493481/04c51542-c734-4864-845e-fc97e26aaad8)
