### ISSUE TITLE
Retire the excel import endpoint

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#580]
The old excel import mechanism has not been used for a while and can be retired

1. The code has not been tested for a while, and is most probably broken
2. We already have an alternative - the csv import mechanism that is continuously being used and works asynchronously. 

### Acceptance criteria
- Remove "/excelImport" endpoint
- Cleanup code
- Cleanup documentation

**Comment by mahalakshme** [comment]
@vinayvenu unable to find this endpoint in server code.

**Comment by vinayvenu** [comment]
This was done as part of avniproject/avni-security#6
