### ISSUE TITLE
Sync does not delete/remove beneficiaries if fast sync is set up

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-server#585]
**Describe the bug**
If a user has fast sync setup and is later given a sync attribute, ideally it should get data/records according to the sync attribute. (Irrespective of whether the user has fast sync setup or not).

Right now it fetches data that was present in the fast sync db, and then the data according to the sync attribute.

**To Reproduce**
1. Have a user that has some data against the user-assigned catchment.
2. Set up fast sync to that catchment.
3. Assign a sync attribute to that user.
4. Fresh sync on your device.
5. You must be able to see some data was backed up by fast sync and the data related to the sync attribute present.

Desired outcome: 
The device should have data that is within the boundary of sync criteria (attribute + catchment)

**Comment by himeshr** [comment]
After discussion with Vinay, we have come up with a few points of consideration:
 - If we have a change in sync-attribute value, then that calls for reset sync for a User. But with a Fast-sync, we would have loaded values belonging to catchment, without caring for mismatch in the sync-attribute values.
 - If we were to have fast-sync for catchment and sync-attributes associated correctly for source-user(who created fast sync) and current user, even then, we need a way to transfer metadata corresponding to source-user, as this would ensure modification of sync / resets happening correctly after fast-sync and before we start regular sync from the time after the cut-off values specified in the fastSync file.
 

Considering that there are several points of consideration, we are not yet ready to start development on this card. Moving it to 'Needs Analysis' and removing the 5.0-release tag.

**Comment by mahalakshme** [comment]
This is part of a bigger issue where fast sync doesn't handle any cases other than catchment: https://github.com/avniproject/avni-client/issues/956
