### ISSUE TITLE
All subjects do not get synced immediately to client phone for APFOdisha user

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#587]
**Describe the bug**
One of the issues around sync encountered during ticket resolution for APFOdisha was that, Beneficiary records got synced to the client phone after a while.(1 hour)

**To Reproduce**

1. Have a user that has some data against the user-assigned catchment.
2. Assign a sync attribute to that user.
3. Fresh sync on your device.
4. You must be able to see a different in the count of Registrations synced to the device, vs the expected number based on Output of this SQL query:
```
select i.uuid
 from public.individual i where i.address_id in (select id from address_level where id in(
  select addresslevel_id from virtual_catchment_address_mapping_table vcamt
  where catchment_id = 10085) and is_voided is false
)
                                                                  and i.sync_concept_1_value = '8ebbf088-f292-483e-9084-7de919ce67b7'
  and is_voided is false and i.subject_type_id = 672 and i.sync_concept_2_value is null ;
;
```

** Desired outcome: **
The device should have all data that is within the boundary of sync criteria (attribute + catchment) synced to the device in the first full sync itself

**Comment by himeshr** [comment]
Related to #585

**Comment by nupoorkhandelwal** [comment]
It has come through Support ticket as well- https://avni.freshdesk.com/a/tickets/2954
 
PFA screenshots of same user's login on two different devices, even after syncing the app multiple times at the same moment, there are differences in the numbers -


![WhatsApp Image 2023-08-10 at 13 14 23 (1)](https://github.com/avniproject/avni-server/assets/37863085/f015b78e-7243-45bc-a056-c2df326b4749)

![WhatsApp Image 2023-08-10 at 13 12 20](https://github.com/avniproject/avni-server/assets/37863085/98f5216a-657e-402b-8bf5-985ab884579d)

**Comment by petmongrels** [comment]
@himeshr @nupoorkhandelwal 
I tried FRESH SYNC on a user which had sync attributes - as mentioned in the card. This is not reproducible. It will require environment and user details.

**Comment by petmongrels** [comment]
@himeshr this is a non-issue. the subject type allows only sync for village/hamlet. this is not incorporated in your query as the catchment has Priject/block as well

**Comment by himeshr** [comment]
## Response for below query is 1629, where we **do** filter on address_level.typeId to restrict to only "Village/Hamlet":
```
select count(i.uuid)
from public.individual i where i.address_id in (select id from address_level al
    where id in(
    select addresslevel_id from virtual_catchment_address_mapping_table vcamt
    where catchment_id = 10085) and type_id = 883 and is_voided is false
)
                           and i.sync_concept_1_value = '8ebbf088-f292-483e-9084-7de919ce67b7'
                           and is_voided is false
                           and i.subject_type_id = 672
                           and i.sync_concept_2_value is null ;
;
```

## Response for below query is 1639, where we **do not** filter on address_level.typeId to restrict to only "Village/Hamlet":
```
select count(i.uuid)
from public.individual i where i.address_id in (select id from address_level al
                                                where id in(
                                                    select addresslevel_id from virtual_catchment_address_mapping_table vcamt
                                                    where catchment_id = 10085)
--                                                   and type_id = 883
                                                  and is_voided is false
)
                           and i.sync_concept_1_value = '8ebbf088-f292-483e-9084-7de919ce67b7'
                           and is_voided is false
                           and i.subject_type_id = 672
                           and i.sync_concept_2_value is null ;
;
```

We used to observe this difference of 10 entities or so earlier as well and assumed it was due to partial sync due to subjectMigration or SyncConceptValues, but turns out it was due to LocationHeirarchy filter missing in our query.

Closing this, as its working as expected.
