### ISSUE TITLE
Implement PATCH /api/subject

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#589]

**Comment by vinayvenu** [comment]
1. Is it ok to change subject type on a patch api? 
2. Tests

Unrelated commits
- https://github.com/avniproject/avni-server/commit/834b883798d101c89bf3794a97c18c476bbc0200
- https://github.com/avniproject/avni-server/commit/c450953edae45c6797dd4d98329fba14a62ebfd6
- https://github.com/avniproject/avni-server/commit/35ea722482178b6efe8b138588a4cb3aa63b4ba7

**Comment by petmongrels** [comment]
We have been allowing changing subject type via update API
