### ISSUE TITLE
Implement PATCH api/encounter

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#590]

**Comment by vinayvenu** [comment]
1. We should validate the encounter type only from the existing encounter's encounter type. Currently the IllegalArgumentException for "Encounter type not found..." is dead code because we already checkEncounterPrivilege before reaching here. 
2. Tests

**Comment by AchalaBelokar** [comment]
- [ ] Null value is not accepting here

**Comment by mahalakshme** [comment]
Looks like Vinay's comments are not addressed.

**Comment by ashusvnath** [comment]
To Vinay's comments 
1. The checkEncounterPrivilege method does indeed check for a non null UUID but doesn't go beyond and does a plain return when corresponding encounter type is null. My worry is that Encounter type being null will break the rest of the code if not verified.  Hence I have not removed the code.
2. Tests are on their way, need to look at all the dependencies and setup mocks before test starts giving value.

**Comment by mahalakshme** [comment]
@ashusvnath Looks like patchEncounter private method and calling methods on encounterRepository can be moved to service, to  prevent controllers from becoming bulky.

**Comment by ashusvnath** [comment]
@mahalakshme : have moved the patch method to encounter service.
