### ISSUE TITLE
Translations API

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#60]
### Motivation
As a dataentry app I want to get translation data so we can support different locales.

### Acceptance Criteria
- Return data for all locales available in the org config of the system.
- Give an optional query parameter locale which allows user to get translation data only for the given locale.
- The translation table data should override platform_translation table data in the response. E.g. if there is a key in platform_translation table by name "cancel" and value is "Cancel" but there is a key by same name in translation table with value "Cancel it" then in the response we should return just one key "cancel" with value "Cancel it.

### Request
```
GET /web/translations
Optional query string parameter: locale={locale code}
```

### Happy path Response
```
{
  "en": {
    "cancel" : "Cancel",
    "getLocation" : "Get GPS Location"
  },
"hi_IN"": {
   "cancel" : "कॅन्सल करें",
   "getLocation" : "जीपीएस लोकेशन प्राप्त करें"
 },
...
}
```

### Exception path Response
```
When no query parameter is passed and data is not available for some locale we will not return any data for it. E.g. if there is data available for English but not for Gujarati we will return:
{
  "en": {
    "cancel" : "Cancel",
    "getLocation" : "Get GPS Location"
  }
}
When no query parameter is passed and data is not available for any language we will return HTTP 404.
If the query parameter is passed and there is no data for that parameter we will return HTTP 404.

```

### Tech Approach
We have translation data available in two tables: platform_translation and translation. The platform_translation table is the default translation data that is available in the avni system. The translation table is the translation data provided by the organisation using the app. When we are returning the data we will have to return the merged data from both tables. The translation table data should override platform_translation table data in the response.

**Comment by amolnirmalpsl** [comment]
No one
￼
@amolnirmalpsl working on it

**Comment by hithacker** [comment]
@amolnirmalpsl are you working on this currently?
