### ISSUE TITLE
Unable to fetch tasks with metaData concepts QueryParam filter

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#606]
## Details
Issue encountered in Staging env only not in production.
This is a regression caused in 5.o release in Tasks GET API.

### Request:
METHOD: GET
URL: {{protocol}}://{{host}}:{{port}}/api/tasks?metadata=%7B%22Number%22:%2209667098331%22%7D&type=Call&isTerminalStatus=false

### Response: 
Status: 400 Bad request
Error: Bad Request: concepts parameter is not a valid json object

### Prod env success screenshot
![Image](https://github.com/avniproject/avni-server/assets/72493481/dea6e240-c80f-41ba-b8e4-8c387c8aa62b)

### Staging env Error screenshot
![Image](https://github.com/avniproject/avni-server/assets/72493481/22e1256a-126b-45fb-a011-e0a5fdfebbf5)

**Comment by petmongrels** [comment]
details here: https://github.com/avniproject/avni-security/issues/7#issuecomment-1722955591
