### ISSUE TITLE
High response time on avni-server

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#607]
Our average response time is hovering at 800+ ms without much change in the throughput. Needs to be investigated. 

#### Primary issue
Response times frequently going above the 500ms threshold. Sample from the past 3 hours. Notice the lowest point is 0.41 (only 41% requests served well). 3 months ago, we were consistently at the 0.9 range. Notice this is without too much change in the throughput. 

![Image](https://github.com/avniproject/avni-server/assets/344222/d6bb5860-2c13-4901-a574-53782bd31062)

#### Investigation
New query with 6% usage

![Image](https://github.com/avniproject/avni-server/assets/344222/b0d8246f-378b-46fd-92c1-3aa709f2e8e4)

Increase in response time and throughput for subject migration select query

![Image](https://github.com/avniproject/avni-server/assets/344222/41cf3fde-e9fe-48a5-b27f-d84fa35b415d)

**Comment by 1t5j0y** [comment]
### Overall Slower performance
DB seems to be the highest contributing factor (the yellow section in the graph has grown wider).


![Image](https://github.com/avniproject/avni-server/assets/54208632/94d34354-7a11-4aa7-8df1-b9c898aaf7e7)



Read load on the DB has gone up a lot since August 20 (4.0 released) and reduced when ETL was stopped. There is improvement in this since yesterday (Sep 19).


![Image](https://github.com/avniproject/avni-server/assets/54208632/822cce0c-0b32-4301-bec1-34631acd449f)



![Image](https://github.com/avniproject/avni-server/assets/54208632/cc0ef643-5036-44ef-bfdc-6f210df066e6)




### Postgres title_lineage_locations_view select
Query is text based.
Query: ```select lowestpoint_id from title_lineage_locations_view where lower(title_lineage) = lower(?)```


### Postgres subject_migration select
Can added indexes on ```subject_migration``` for ```individual_id```, ```subject_type_id```, ```old_address_level_id``` columns.

Query: ```select subjectmig0_.id as id1_79_, subjectmig0_.is_voided as is_voide2_79_, subjectmig0_.uuid as uuid3_79_, subjectmig0_.created_by_id as created12_79_, subjectmig0_.created_date_time as created_4_79_, subjectmig0_.last_modified_by_id as last_mo13_79_, subjectmig0_.last_modified_date_time as last_mod5_79_, subjectmig0_.version as version6_79_, subjectmig0_.organisation_id as organisa7_79_, subjectmig0_.individual_id as individ14_79_, subjectmig0_.new_address_level_id as new_add15_79_, subjectmig0_.new_sync_concept_1_value as new_sync8_79_, subjectmig0_.new_sync_concept_2_value as new_sync9_79_, subjectmig0_.old_address_level_id as old_add16_79_, subjectmig0_.old_sync_concept_1_value as old_syn10_79_, subjectmig0_.old_sync_concept_2_value as old_syn11_79_, subjectmig0_.subject_type_id as subject17_79_ from subject_migration subjectmig0_ left outer join individual individual1_ on subjectmig0_.individual_id=individual1_.id where (subjectmig0_.last_modified_date_time between ? and ?) and (individual1_.subject_type_id=? or subjectmig0_.old_address_level_id in (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ..(47,942 more chars)```

**Comment by 1t5j0y** [comment]
Separate cards to be created to fix identified issues.

**Comment by mahalakshme** [comment]
Thinking of the scope of our work to fix performance. - From Vinay
1. Fix SubjectMigration sync (add indices) - MUST
2. Add l2 caching to reduce calls to user, concept and concept_answer (can impact a lot of our endpoints including all external APIs) - MUST
3. Get rid of programSummaryRule and getEligible Programs from web app (7% of usage) - SHOULD
4. Fix organisationConfig (low from a performance standpoint, high from a user experience standpoint) - COULD
