### ISSUE TITLE
Redirect to login page broken for unauthorized /web/media calls

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#612]
**Describe the bug**
Redirect to login page broken for unauthorized /web/media calls

**To Reproduce**
1. Open Incognito window in any browser and paste this link in address bar 
https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/gvamp_uat/4af905e5-1c91-41ed-9d82-b560ed48eb95.jpg
3. Page show 401 Un-authorzed error

**Expected behavior**
1. On opening Incognito window in any browser and pasting this link in address bar 
https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/gvamp_uat/4af905e5-1c91-41ed-9d82-b560ed48eb95.jpg
2. App should redirect to login page
3. After login, if organization is correct for targeted url, then media content should be shown

**Workaround**
- Login to the org on avni-webapp before opening the media urls

**Screenrecording**

https://github.com/avniproject/avni-server/assets/72493481/9e397e50-e95c-47b7-b469-088d7d376b94

** Possible fix **
Whitelist the '/web/media' path in Avni-server

**Comment by ashusvnath** [comment]
QA observations:

Navigating to `https://prerelease.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prerelease-user-media/<redacted>` in the browser
1. Takes me to login page if I'm not logged in.
2. Downloads the media link if I'm logged in.
3. Gives a 401 unauthorize if the URL does not  belong to the current organization

Works as specified.
