### ISSUE TITLE
Remove duplicate entries from the subject_migration table

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#618]
### Context
```
select count(*)
from subject_migration sm1
         inner join subject_migration sm2 on sm1.id - sm2.id = 1 and sm1.individual_id = sm2.individual_id;
```

### Acceptance criteria
- Write a migration that removes duplicates (duplicated all parameters, not just the ones mentioned in the context) from the subject_migration table

**Comment by 1t5j0y** [comment]
Count query:
```
select count(*)
from subject_migration sm1
     inner join subject_migration sm2
            on sm1.id - sm2.id = 1
                and sm1.individual_id = sm2.individual_id
                and sm1.old_address_level_id = sm2.old_address_level_id
                and sm1.new_address_level_id = sm2.new_address_level_id
                and sm1.organisation_id = sm2.organisation_id
                and sm1.old_sync_concept_1_value = sm2.old_sync_concept_1_value
                and sm1.new_sync_concept_1_value = sm2.new_sync_concept_1_value
-- and sm1.old_sync_concept_2_value = sm2.old_sync_concept_2_value
-- and sm1.new_sync_concept_2_value = sm2.new_sync_concept_2_value
                and sm1.subject_type_id = sm2.subject_type_id;
```

Delete query:
```
delete
from subject_migration
where id in (
select sm1.id
    from subject_migration sm1
        inner join subject_migration sm2
        on sm1.id - sm2.id = 1
        and sm1.individual_id = sm2.individual_id
        and sm1.old_address_level_id = sm2.old_address_level_id
        and sm1.new_address_level_id = sm2.new_address_level_id
        and sm1.organisation_id = sm2.organisation_id
        and sm1.old_sync_concept_1_value = sm2.old_sync_concept_1_value
        and sm1.new_sync_concept_1_value = sm2.new_sync_concept_1_value
-- and sm1.old_sync_concept_2_value = sm2.old_sync_concept_2_value
-- and sm1.new_sync_concept_2_value = sm2.new_sync_concept_2_value
        and sm1.subject_type_id = sm2.subject_type_id
);
```

Are we doing this as a flyway migration or run manually?

**Comment by mahalakshme** [comment]
- These duplicates are from the server. But they would have synced to the client. So we need to clear the duplicates from the mobile db for consistency of data. The only way I see doing this is getting the 8700 uuids from server and deleting them via client migration. Is there a better way.

- I think we can do as a flyway migration so that it is in the codebase corresponding to the fix we have made to fix the duplicate bug.

**Comment by vinayvenu** [comment]
Duplicate removal from client is not necessarily important because subject migrations are a one-way street that never get read after sync. Also, duplicate identification is hard on the client where we don't have consecutive ids. 

One problem with Flyway migration is that it doesn't provide for sufficient scrutiny when running on production.
Maybe run it as a one-time script instead?

**Comment by vinayvenu** [comment]
@1t5j0y the query needs to work for subject migration entries that do not have sync_concept_1_value. Right now they are missed out in this query because null != null

**Comment by mahalakshme** [comment]
@vinayvenu agreed. But anyways I thought we can do the cleanup for the easy ones as part of this: https://github.com/avniproject/avni-client/issues/1126. We can leave the duplicate removal.

**Comment by mahalakshme** [comment]
We can run this once in prod after testing done and before release  and after release. Before release since these duplicate entries are causing additional calls to GET /subject/{uuid}/allEntities for every new subject migration which makes the sync appear still stuck.

**Comment by mahalakshme** [comment]
I was wrong, it runs only once for one subjectMigration uuid since  we are doing after getting all subject migrations.

**Comment by 1t5j0y** [comment]
Updated the queries in the first comment to handle null !=null.

Couple of questions:
1. Will voiding the dupes be sufficient instead of hard delete?
2. Should we also update the manual_update_history column for the non-dupes to indicate a dupe was deleted?

**Comment by mahalakshme** [comment]
- I think we can hard delete the duplicates considering that will reduce sync time for new users. I consider softdelete is for our users, hard-delete when we make a mistake that causes some repurcussions. 
- I think we can update manual_update_history column for the non-dupes to indicate a dupe was deleted to traceback any issues with hard-delete.
cc: @vinayvenu

**Comment by 1t5j0y** [comment]
Discussion during standup:
1. Verify current sql logic using transactions and rollback on prod and apply directly to prod.
2. Additionally, add as a flyway migration so any duplicates created subsequently are cleared up during 5.0.1 deployment.

Updating script to update manual_updated_history for non-dupe records.

**Comment by 1t5j0y** [comment]
There were cases of 3 dupes in a row so added additional logic to handle those. Please review the sql in data-fixes repo.

**Comment by vinayvenu** [comment]
@1t5j0y looks good. Lets move to flyway.
