### ISSUE TITLE
Enhance the enhanced validations for question group

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#625]
Issue # 6 in [Third Mobile Report](https://github.com/avniproject/avni-security/files/12735192/mobile_report_3.pdf)

The issue as such mentioned in the screenshots is already fixed by us. But they wanted us to do such validations for all POST calls.

Currently for Text form elements we are allowing special characters to be input. We should disallow them.

Acceptance criteria:

- for question group validation, that is not repeatable, validate value is an object and validate the concepts within question group
- for question group validation, that is repeatable, validate value is an array and validate the concepts within each question group. Though repeatable QG not used in Teach for consistency of handling and to prevent app from breaking need to handle this.

Out of scope:
Validations for other data types used in teach are already handled.

**Comment by mahalakshme** [comment]
Why is this in hold @himeshr

**Comment by petmongrels** [comment]
Concept.isQuestionGroup lets use boolean instead of Boolean where we have only two states.

**Comment by petmongrels** [comment]
two issues.
1. in QG obs non-numeric is allowed for numeric
2. observations on concept outside QG are allowed in the QG

**Comment by himeshr** [comment]
Added fix to handle issues found during QA.
Also added tests for these scenarios.

**Comment by himeshr** [comment]
Validated the fix to check for the two issues reported during QA:
 - in QG obs non-numeric is allowed for numeric (d57c3ffd-3cbd-4220-b95f-6968f827d426)
 - observations on concept outside QG are allowed in the QG
 
<img width="1840" alt="Screenshot 2023-10-17 at 2 18 03 PM" src="https://github.com/avniproject/avni-server/assets/72493481/4234d90e-3f9d-4cac-bb72-6715062bf1e3">

<img width="1840" alt="Screenshot 2023-10-17 at 2 17 50 PM" src="https://github.com/avniproject/avni-server/assets/72493481/f6bdeb56-d59c-4f84-914a-85e5cd682350">

 This was happening only for NonRepeatableQuestionGroups.
