### ISSUE TITLE
Remove lookup by lowest address level during subject csv upload

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#627]
When uploading subjects through csv, we do the following to fetch addresses
1. Look up the lowest address level and check for matches
2. If there are multiple matches, then take the entire address hierarchy and look up address_level table

The first lookup is redundant now because we never use it. It also performs badly because we currently fetch all address levels and do the lookup in Java. 

### Acceptance criteria
- Lookup of addresses based on lowest address level is removed

**Comment by vinayvenu** [comment]
This change needs to be applied to 4.0 branch and deployed to the LFE production server.

**Comment by mahalakshme** [comment]
@vinayvenu so basically the performance increased because we are now not reading all the address levels from the csv when lowest address level matches is it?

**Comment by vinayvenu** [comment]
@mahalakshme The primary change is to replace the original mechanism of reading all address levels from the **database** and then comparing with the lowest address level in the csv. Instead, we make a direct call to database with the filter.
