### ISSUE TITLE
Reduce the data ingested to NewRelic

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#644]
### Acceptance criteria:
We are on a free plan in Newrelic and it allows only 100GB of data/month. We breached this limit last month. See if some data ingestion to newrelic can be avoided or reduced to make sure we can continue using newrelic on all days.

### Additional details:
To check the above, after logging into newrelic click on 'VinayVenu' profile icon on the bottom left -> Click 'Manage your data' to view the splitup of the ingested data across days.

**Comment by vinayvenu** [comment]
Logs were enabled for integration service. Disabled it.
