### ISSUE TITLE
Write and execute update SQL to cater to change in subject migration logic

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-server#647]
Update last_modified_date_time for all affected entities for migrated subjects in all orgs to cater to change in subject_migration logic and to prevent association errors.

Refer to the script created for APF Odisha as part of #640 

https://github.com/avniproject/APF-Odisha/blob/ca630a7605a2e764f8ca26fff51a945405506690/server-640/data-fix.sql#L6C1-L98C151

### Updated description - 8/11:
- The above APF Odisha script caters to only migration from AWC to Village. Other cases of address migration(Village to village, AWC to AWC and Village to AWC) for APF Odisha need to be handled in the script added for this card.

### How to test:
1. Refresh prereleasedb with proddb since data fixes run on prod for APF not present in prerelease yet. Steps here: https://github.com/avniproject/avni-server/issues/647
2. Dump of AS4@jnpct (joyapre@jnpct is setup for this catchment as well) in this ticket: https://avni.freshdesk.com/a/tickets/3210 can be uploaded to prerelease S3 - ***this is already in place***
3. Sync with login as AS4@jnpct - sync will fail with issue in the ticket
4. Run the script of this card on prerelease
5. Sync with login as AS4@jnpct - sync should succeed

**Comment by 1t5j0y** [comment]
Filtered entries based on org not being APF Odisha and subject migration record being created before 5.0.1 release. Script added to data-fixes repo.

**Comment by mahalakshme** [comment]
APF odisha script was run for only migrations from AWC to village. It doesn't cater for migration from village to village. There is an ongoing discussion to see if the fast syncs of APF odisha users can be deleted. So this can be considered out of scope of this card.

**Comment by 1t5j0y** [comment]
@mahalakshme not clear what you meant. The script already excludes apfodisha records.

**Comment by mahalakshme** [comment]
@1t5j0y there is this condition in the script: ```where old_address_level_id in (select id from address_level where type_id = 886 and is_voided = false)
                                             and new_address_level_id not in (select id from address_level where type_id = 886 and is_voided = false))```

**Comment by 1t5j0y** [comment]
@mahalakshme looks like you've reviewed the wrong script. Please look at the script tagged to this issue in the data-fixes repo as mentioned above.

**Comment by mahalakshme** [comment]
@1t5j0y I meant the APF odisha script has this condition: ``` where old_address_level_id in (select id from address_level where type_id = 886 and is_voided = false) and new_address_level_id not in (select id from address_level where type_id = 886 and is_voided = false))``` Just commenting for clarity for who looks thru the comments. I understand the above is old comment before standup discussion.

**Comment by 1t5j0y** [comment]
Tested on prerelease and executed on prod.
Prod run log attached.

[647_datafix_runlog.txt](https://github.com/avniproject/avni-server/files/13306169/647_datafix_runlog.txt)

Verified counts as 0 result after execution.
