### ISSUE TITLE
API to fetch subject encounters

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-server#65]
Required to render Subject Dashboard General tab.

### Request
```
GET /web/subject/{subjectUuid}/encounters
```

### Happy path Response
```
{
  "encounters": [
    {uuid, name, operationalEncounterTypeName, encounterDateTime, earliestVisitDateTime, maxVisitDateTime}
  ]
}
```

### Exception path Response
404 if subject not found

**Comment by github-harshal-ghisad** [comment]
On staging

1. Wrong API returning error, used postman plugin
PASS
2. API returns encounters
PASS
