### ISSUE TITLE
Remove Calcutta Kids dependency on its parent!

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#655]
### Motivation:
I want to remove the parent organisation dependency to gain independence for adding/modifying details specific to child orgs on forms that belong to parent orgs.

### Analysis:
- This is related to this card:
https://github.com/avniproject/calcutta-kids/issues/78
- Implementation team has come up with these SQL queries(https://github.com/avniproject/calcutta-kids/blob/master/migration.md) to achieve this. 

### Objective:
1. Plan for the migration and schedule a down-time for the operations
2. Achieve removal of the parent organisation dependency in a simpler, less error-prone and a more generic manner since this needs to be repeated for IHMP sooner.
3. Come up with a backup plan to revert the changes if needed.

### Dry Run 
- Perform the migration tasks in prerelease organisation first and then validate the changes
- Ensure that we do not change CK org user credentials

### Acceptance criteria:
   - Take a dump (with transactional data) of the org to be migrated for backup purpose
   - Remove parent_organisation_id from the organisation table for the child org.
   - Then import org1 bundle to the child org.
   -  ~Currently going to Organisation1 with super admin login breaks. Check if this can be fixed easily. If this doesn't work come up with a approach to migrate the metadata from org1.  By doing via bundle upload we can mitigate reference issues that occur within metadata tables(eg: concept_answer referring concept or form_mapping referring subject and encounter)~ Fixed the openchs_org_admin login and bundle download issue
   - Update transactional data to refer the new imported metadata: Refer to these SQL queries(https://github.com/avniproject/calcutta-kids/blob/master/migration.md) to achieve this. 

   Eg: relationship_type_id in individual_relationship table should not anymore point to the org1 data. Achieve this by getting a list  of columns from transactional tables that refers columns of metadata tables and changing the reference.

   - ~Migrate old_rules. ```calcutta_kids``` repo have old rules which are deployed using the command ```make deploy-staging-rules``` and ```make deploy-prod-rules``` after doing ```make deps```. Deploy the old rules to the new orgs created by modifying the config on the Gruntfile.~ Since we are doing this on the same child org, no need to upload old rules again.
   
- Evaluate impact of migration out Org1 on ETL process for the child org (If issue occurs, does recreate of etl schema fix it?)

### Testing

   - Test DEA and mobile app to check everything works as expected. nothing more(eg: extra encounter forms) or anything less/different should be displayed when compared to before. Old rules need to work. Sync need to work.

**Comment by petmongrels** [comment]
All - lets discuss the approach.

**Comment by petmongrels** [comment]
In the order of dependency of foreign keys. Two of set SQLs.
- insert into metadata tables with exact same values (including uuid). resolve foreign keys during the insert only, as the updates later is complicated.
- update transaction data in one query each per entity

Lets discuss if it is any more complex than this.

**Comment by mahalakshme** [comment]
@petmongrels  if we can do bundle upload from org1 we need not insert into metadata tables.  At worst case(when we need to do metadata insert) it doesn't seem more complex than the above 2 sets.

**Comment by petmongrels** [comment]
yes I think we can try this approach, with user superadmin (dbUser openchs_impl). I wonder where the password for this user is.
Maybe we will have to upload via postman as without parent org, web app may not work to be able to upload.

**Comment by mahalakshme** [comment]
@petmongrels yeah we can create a admin user for the parent org if it doesn't exist manually(inserting into db and cognito) as well and then download metadata zip from parent org and login as the admin user of the new  org and upload.

**Comment by ashusvnath** [comment]
Currently facing an issue where form_mapping for subject type individual is null.
Tried to fix data by mirroring production, but it didn't help.

**Comment by himeshr** [comment]
[prereleaseExecutionCommands.txt](https://github.com/avniproject/avni-server/files/13495989/prereleaseExecutionCommands.txt)
Uploaded the psql file containing actual commands executed on prerelease db to perform removal of dependency on Org1 for CalcuttaKids(org19).

**Comment by mahalakshme** [comment]
@himeshr push the SQL to https://github.com/avniproject/data-fixes/tree/main - data fixes repo

**Comment by himeshr** [comment]
As discussed in standup, we'll retain the migration script in Calcutta_kids org.
The file is just for reference, all sql commands are based on migration.md file in Calcutta_kids org repo.

**Comment by mahalakshme** [comment]
- so the bundle upload took care of having the right gender_id in  individual_relation_gender_mapping table is it? asking since gender is created via SQL and individual_relation is imported via bundle
- update manual_update_history column, using append_manual_update_history function for the applicable tables
- Didnt understand this: https://github.com/avniproject/calcutta-kids/blob/3242fe75162e1bd30c418fb5db9e328bdbddf446/migration.md?plain=1#L546C92-L546C92 - org 1 doesn't have old rules, so rules should work as before or with deployment of old rules to the org - I suggest testing this before moving to QA Ready

**Comment by himeshr** [comment]
> * so the bundle upload took care of having the right gender_id in  individual_relation_gender_mapping table is it? asking since gender is created via SQL and individual_relation is imported via bundle
> * update manual_update_history column, using append_manual_update_history function for the applicable tables
> * Didnt understand this: https://github.com/avniproject/calcutta-kids/blob/3242fe75162e1bd30c418fb5db9e328bdbddf446/migration.md?plain=1#L546C92-L546C92 - org 1 doesn't have old rules, so rules should work as before or with deployment of old rules to the org - I suggest testing this before moving to QA Ready

- Yes, individual_relation_gender_mapping had relevant entries created automatically through bundle upload
- added set of manual_update_history column, using append_manual_update_history function for the transactional data tables
- CK has old rules, which should work as is, as the metadata entity uuids would still remain the same.

**Comment by himeshr** [comment]
@AchalaBelokar I've successfully restored prod db to prerelease and rerun migration without making changes in lastModifiedDateTime for any of the entities.
Please test this using 2 users: himesh and achala

**Comment by AchalaBelokar** [comment]
- [ ] I added children in individual  still I am not able to enrolled mother program. Individual name is Shnd Bene and added  child name is sami sami, ... user is AchalaB

**Comment by himeshr** [comment]
> * [ ]  I added children in individual  still I am not able to enrolled mother program. Individual name is Shnd Bene and added  child name is sami sami, ... user is AchalaB
> 
>  az_recorder_20231204_135303.mp4

This is was caused as the individual was a male when the child was linked to it as a son.
Achala then changed the gender and attempted to enrol to Mother program, where the relation with the son was actually father.

Therefore this is a wrong user action issue and doesnot need additional fix.

**Comment by vedfordev** [comment]
@himeshr and @sachsk , while working on CK ETL in pre-release for reporting purposes, i found the following duplicate concepts for the forms and the corresponding fixes done to unblock etl

```sql
-- List of form_elements with same concept within a single form

select f.name,c.id,count(*), max(fe.id)
from form f
         join form_element_group feg on f.id = feg.form_id
         join form_element fe on feg.id = fe.form_element_group_id
         join concept c on fe.concept_id = c.id
where f.is_voided = false
  and feg.is_voided = false
  and fe.is_voided = false
group by f.name,c.id
having count(*)> 1;


-- List of Form-element and related entity names within a form having same concept
select fe.id, f.name, fe.name, feg.name from form_element fe
                                                 join form_element_group feg on fe.form_element_group_id = feg.id
                                                 join form f on f.id = feg.form_id
where concept_id = 211135 and fe.is_voided = false;



-- Fix to void latest form_element which has same concept in twice in same form
update form_element set is_voided = true, last_modified_date_time = now()
where id in (
             110147,110146,110140,110139,110136,110018,109953,109951,109950,109921,109895,109892,109889,109887,109883,109873,109870,109834,109832,109825,109806,109805,109804,109803,109801,109788,109785
    );

-- Fix to void all form_elements related to concept with id 210804, as its repeated more than twice in same form across multiple forms
update form_element set is_voided = true, last_modified_date_time = now() where concept_id = 210804;
```

**Comment by mahalakshme** [comment]
Looks like the above has also led to the second issue mentioned here: https://github.com/avniproject/avni-client/issues/1253#issuecomment-1870966134

**Comment by himeshr** [comment]
> Looks like the above has also led to the second issue mentioned here: [avniproject/avni-client#1253 (comment)](https://github.com/avniproject/avni-client/issues/1253#issuecomment-1870966134)

This issue is in Prod Environment of Calcutta Kids and is caused by multiple FormElements using same concept.
Therefore, it is not related to CK Migration.
```sql
set role calcutta_kids;
select c.id,
       c.name,
       fe.id,
       f.name,
       fe.name,
       feg.name
from form_element fe
         join form_element_group feg on fe.form_element_group_id = feg.id
         join form f on f.id = feg.form_id
         join concept c on fe.concept_id = c.id
where
--         c.id = 672;
      fe.name = 'Colour of child'
  and fe.is_voided = false
  and feg.is_voided = false;


```
## SQL Output
```text
id,name,id,name,name,name
672,Colour of child,398,Birth form,Colour of child,Physical Examination
672,Colour of child,1422,Birth form,Colour of child,Physical Examination
672,Colour of child,1499,PNC Doctor Checkup,Colour of child,Physical Examination


```
