### ISSUE TITLE
update last_modified_date_time on the last modified encounters

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#658]
ticket: https://avni.freshdesk.com/a/tickets/3234?lang=en but didn’t update last_modified_date_time.

```begin transaction;
update encounter
set address_id = individual.address_id,
   manual_update_history = 'ticket-3234'
from individual
where individual.id = encounter.individual_id and individual.address_id <> encounter.address_id;
select count(*) from individual
                        join encounter e on individual.id = e.individual_id
where e.address_id <> individual.address_id;
commit;
```

So to do now: 

update encounter set last_modified_date_time=current_timestamp, last_modified_by_id=11084
where manual_update_history='ticket-3234';

**Comment by vinayvenu** [comment]
https://github.com/avniproject/lfeteach/blob/main/Migrations/FD-3234-part-2.sql

**Comment by vinayvenu** [comment]
Deployed to prod. Closing
