### ISSUE TITLE
add subject_migration entries for those that are missing

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#659]
The migrated individuals will still be in the user’s db. To fix this entry for the migration needs to be made in the subject_migration table.

For each update for individual entry in the script need to do this:
Lets take first one: old address id: 68142, new address id: 145191

Step 1: Find the individuals(both voided and not voided) who are migrated from the old to new address:

``` 
select * from individual where manual_update_history='Updating individuals address id from old one to new one as per client request'
                          and address_id = 145191; 
```

These are the individual ids: 111851, 111857, 112419, 106551, 106552, 106554, 106555, 106556, 106553, 216695, 216945, 217386, 215956, 216065

Step 2: For each of the above individual insert into subject_migration table: lets take first individual: 111851

``` 
insert into subject_migration (uuid, individual_id, old_address_level_id, new_address_level_id, organisation_id,
                              audit_id, is_voided, version, created_by_id, last_modified_by_id, created_date_time,
                              last_modified_date_time, old_sync_concept_1_value, new_sync_concept_1_value,
                              old_sync_concept_2_value, new_sync_concept_2_value, subject_type_id)
values (uuid_generate_v4(), 111851, 68142, 145191, 4, create_audit(),false,0, 11084, 11084, now(), now(),
       null, null, null,null, 4); 
```

**Comment by vinayvenu** [comment]
https://github.com/avniproject/lfeteach/blob/main/Migrations/FD3245.sql

**Comment by vinayvenu** [comment]
Deployed to prod. Closing.
