### ISSUE TITLE
Enable recording for Exotel masked calls

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#661]
Ticket: https://avni.freshdesk.com/a/tickets/3264

### AC:
Since the Exotel API has changed without backward compatibility being provided(v1 version of API call we are using has changed) in `callMasking` method set the Record parameter to true.

### To test:
Test using Exotel credentials available in Keeweb.

### Reference:
https://developer.exotel.com/api/make-a-call-api#call-customer

**Comment by ashusvnath** [comment]
@mahalakshme : Should "Record" be set to true for all calls or will it be part of request parameter ?

**Comment by vinayvenu** [comment]
@mahalakshme This is temporarily ok to go. We need a followup where we make this value configurable in the exotel configuration.

**Comment by ashusvnath** [comment]
@vinayvenu : I verified that the Record parameter accepts the sting 'true' by manually invoking API using postman.

**Comment by mahalakshme** [comment]
@ashusvnath commit needs to be also put in 5.1 branch for 5.1.3 release

**Comment by ashusvnath** [comment]
@mahalakshme Done

**Comment by himeshr** [comment]
Using Exotel GET Bulk CallDetails APIs, we verified that the recordingUrl is available for the calls made with this fix.
