### ISSUE TITLE
Managing direct assignments of individual to user

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#663]
https://avni.freshdesk.com/a/tickets/3263

#### Current scenario:
Currently individual unable to assign to a user (https://github.com/avniproject/avni-client/issues/1058). They are assigned via group assignment. But we should be able to assign individuals also to user.

#### Premise:
Individual assignment to users should be possible independent of group assignment to the users, since the group that the individual belongs to might change or identified at a later point of time.

#### Acceptance criteria:

- Able to assign individual to a user 
- When a assigned individual to a user, is added to group not assigned to a user, group should not be synced and individual should be synced
- When a group is assigned to a user, like now assign all individuals in the group to the user - already done but make sure to retain the behaviour
- When a new member added to a group assigned to a user,  the member should be assigned to the user - already done but make sure to retain the behaviour
- When a group is unassigned from the user, individuals in the group should continue to remain assigned to the user 
- When a individual is tried to unassign from a user, but group in which individual belongs to is assigned to the user, user should not be able to do this and get a error message that states 'individualName{say Arun} cant be unassigned from the userName{say Rahul}, since group, groupName{say Class12} that individualName{say Arun} belongs to, is assigned to the userName{say Rahul}. 
- On bulk unassignment, when some of the individuals has above issue, do not save any of them. Collate the errors and display. 

#### Corner Test cases:
- Say a individual is assigned to a user, and then a group that individual belongs to is assigned to the user - should work without failing
-  On bulk assign of individuals to a list of users(where some have the individual already assigned) - should work

**Comment by himeshr** [comment]
Dev testing screen recordings are attached here-in:

https://github.com/avniproject/avni-server/assets/72493481/17e3843d-e37e-4501-a5ab-7defa63950dc


https://github.com/avniproject/avni-server/assets/72493481/11bf0b70-0530-45be-b68e-c5d3ed133550

**Comment by mahalakshme** [comment]
@petmongrels are you reviewing this?

**Comment by himeshr** [comment]
When a non-group individual is assigned to a user, but its group is not assigned to the same user, we will get error in client during sync, as it would not find the related Group entity.
As a fix, throw an exception of type OptionalDependentEntityNotFound and handle the same during persist to ingore only those specific entities.

**Comment by himeshr** [comment]
> When a non-group individual is assigned to a user, but its group is not assigned to the same user, we will get error in client during sync, as it would not find the related Group entity. As a fix, throw an exception of type IgnorableSyncError and handle the same during persist to ingore only those specific entities.

GroupSubject groupOrHouseholdSubject init is no longer a IgnorableSyncError, as GroupSubject mappings will only be synced if the groupOrHouseholdSubject is also synced to the User

**Comment by petmongrels** [comment]
It seems there is a scenario which was not supported in Avni so far, but need to be :-)

### Given
- household1 and individual1 exist in a catchment and are linked
- household1 is assigned to userA (this assigns household and individual both to userA)
- individual1 is assigned to userB

### Currently
- we throw error Individual (%s) cant be unassigned from the user (%s), since group (%s) that the member (%s) belongs to, is assigned to the user (%s)

### Should be
- previous assignment should be maintained and a new assignment should be created

**Comment by himeshr** [comment]
> * we throw error Individual (%s) cant be unassigned from the user (%s), since group (%s) that the member (%s) belongs to, is assigned to the user (%s)

@mahalakshme and @vinayvenu 
This is also supported in the current version of code. Resolved the doubt on call with Vivek.
Moving to QA Ready.

**Comment by himeshr** [comment]
@petmongrels Have done this additional commit, because, for the case where Household is within the User's catchment but a Member isn't we would have ended up with a sync error, as we do not (and cannot) check for GroupSubjectMapping -Member being within catchment during syncable items determination on server.

**Comment by AchalaBelokar** [comment]
- [x] Created a student which is not part of any group and assign and unassigned to the user. it is working properly
- [x] Then created a student which is part of one group and then I assigned that group to user and try to unassigned that user it through the error

**Comment by AchalaBelokar** [comment]
- [ ] I am trying to assign single student to the user it is showing me this error.

https://github.com/avniproject/avni-server/assets/104890488/7f86842b-ed8c-484a-8554-d64c5b5253cc

@himeshr can you look at this

**Comment by himeshr** [comment]
> * [ ]  I am trying to assign single student to the user it is showing me this error.
> 
>  Screen.Recording.2023-12-18.at.4.47.21.PM.mov 
> @himeshr can you look at this

I have added debounce to avoid invoking the backend api repeatedly when user keeps clicking on a username.
Should work fine once the webapp fix is deployed.

**Comment by Dinesh2019** [comment]
1.Taking time to select the assigned to user 
2.If we select the user in the assigned to and select the check box under name it is getting refreshed the assign to or remove the user from the assign to 


https://github.com/avniproject/avni-server/assets/127730126/fac65503-635e-43da-bcff-4f588d0823e0

**Comment by himeshr** [comment]
> 1.Taking time to select the assigned to user 2.If we select the user in the assigned to and select the check box under name it is getting refreshed the assign to or remove the user from the assign to
> 
>  Screen.Recording.2023-12-19.at.11.56.01.AM.mov

@Dinesh2019 Create a separate bug, the Individual is correctly assigned / unassigned from the user the first time around.
Its just that on clicking the checkbox, it gets reset to initial state.

**Comment by Dinesh2019** [comment]
@himeshr created the bug card  https://github.com/avniproject/avni-webapp/issues/1106

**Comment by himeshr** [comment]
@AchalaBelokar, we've made an additional commit related to this card. To update the last modified date time for all UserSubjectAssignment and GroupSubject entities.

Therefore, please perform another round of testing for LAHI org DirectSubjectAssignment to User feature, 
1. for catchments where there is missing Students for a KarigarBatch
2. for multiple users with different catchments
3. with old and new prerelease apks

**Comment by AchalaBelokar** [comment]
- [ ] Assign individual to user
- [ ] Assign group individual  to user which contain user
