### ISSUE TITLE
Unable to sync in staging for IHMP

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-server#665]
**Describe the bug**
We are unable to sync after doing changes or registering new individuals. 

**Info**
Environment : Staging
Org : IHMP
User : vedantr@ihmp 
GitBranch : 5.1.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Do fresh sync 
2. try to register individual.
3. try to sync.
4. Check Exception.

**Expected behavior**
User should able to sync

**Screenshots**

<img width="296" alt="Screenshot 2023-11-30 at 1 01 16 PM" src="https://github.com/avniproject/avni-server/assets/106894932/206f6689-2780-4523-82e3-f4973880377e">

**Comment by mahalakshme** [comment]
@vedfordev add the name of uploaded user db, since the issue was when pushing data via sync.

**Comment by vedfordev** [comment]
@mahalakshme  adhoc-dump-as-zip-3e853988-b5f0-44e8-96e0-c992d93b0ae8
