### ISSUE TITLE
LFE specific patch for not allowing date time values in time field

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#674]
- this patch is only to get to the root of the issue by blocking the users from syncing data and hence raising support request
- need not be merged to 6.x, master
- do only for encounter
- throw error if string is not null or great than 5 chars
- by failing the user, it allows ETL process to continue un-interrupted

after Deployment
- at the time of deployment check if there any records with datetime in db then make them null using data fix sql done earlier
- Move the flag "lfe_prod" to latest commit done as part of this card on 5.1.0 branch on avni-server
- close the ticket

**Comment by himeshr** [comment]
Completed testing the encounter save with time dataType concept, for success and error scenarios.

[errorWithInCorrectTimeFormat.txt](https://github.com/avniproject/avni-server/files/13783849/errorWithInCorrectTimeFormat.txt)
[successWithCorrectTimeFormat.txt](https://github.com/avniproject/avni-server/files/13783851/successWithCorrectTimeFormat.txt)

**Comment by himeshr** [comment]
Completed following steps as part of deploy:
- applied data-fix in db to make them null using update sql
- Moved the flag "lfe_prod" to latest commit done as part of this card on 5.1.0 branch on avni-server
- didn't need to update [this](https://docs.google.com/spreadsheets/d/1LcyE3_Ht_YztBjfPpedvjUtvzcJezP5dFOZFOyzWs2E/edit#gid=0) sheet
- closed the ticket https://avni.freshdesk.com/a/tickets/3342
