### ISSUE TITLE
Duplicate EAS records created during sync for organisation that uses both approvals and media in encounter

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#678]
### Reproduce
- akrsp. staging.
- perform scheduled encounters that have approval enabled and has media fields (jan chaupal e.g.)
- sync
- see duplicate EASes created on server for the same encounter in pending status

**Comment by petmongrels** [comment]
### What to test
- Approval flows (check whether these are getting sycned to server as well)
- Forms with media attached
- Form with both media and approval

**Comment by vinayvenu** [comment]
The server change looks non-backwards compatible. Won't this prevent sync for those who are on an older apk?

**Comment by vinayvenu** [comment]
If there are older implementations, there will be duplicates in the client that won't be available in the server. Need to test that this doesn't cause any issues on the client. In any case, we are still going ahead with this change.

**Comment by Dinesh2019** [comment]
Still we get the duplicate entries attached the video for the references 



https://github.com/avniproject/avni-server/assets/127730126/271dc37d-d2d6-40b6-99da-85f325925521

**Comment by petmongrels** [comment]
The query used is incorrect because it is not checking whether the status is approved or pending. The two entries in are in two different status - which is allowed. We do not overwrite the previous entry.
The fix in this card was to not allow Pending on top of another Pending. Approved after pending is valid.
