### ISSUE TITLE
Hard delete unapplicable concept answers

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#682]
https://avni.freshdesk.com/a/tickets/3371

### Need:
For the first part(for the concept: Are you availing any social security schemes) of the ticket, already handled as part of [this](https://github.com/avniproject/avni-webapp/issues/1110) card.
Similarly handle for second part(issue with concept, Name of the government health facility preferred for chronic illness") of the ticket in a similar manner so that extra columns doesn't appear in the longitudinal export and in the webapp designer. 

### Technical details
But unlike first part, looks like we need not delete the NA type concepts since it is used as answer for a different concept. Looks like need to hard delete only the concept answers to remove the mapping of some of the NA type concept with the concept, Name of the government health facility preferred for chronic illness.

### Process:
Need to go thru' code review before executing on prod.

**Comment by petmongrels** [comment]
@mahalakshme looks like implementation team ticket

**Comment by mahalakshme** [comment]
closing the card because of above.
