### ISSUE TITLE
Fix App Bundle with Group Privilege export import

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#683]
Group Privilege refers to privilege using UUID. But the UUID for some privilege is generated using the uuid_generate function in flyway migration scripts. This makes the privilege export import not work across environments.
Since privilege is managed by the platform it can be referred using its unique Type instead of UUID in the bundle. The types remain the same across environments.
Also ensure that the privilege.type is unique column.

### AC:
Make type in privilege table unique.

**Comment by mahalakshme** [comment]
fixed as part of 9.1.0

**Comment by mahalakshme** [comment]
moved the context to respective cards
