### ISSUE TITLE
Subject type change leads to change in last_modified_date_time

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#686]
Environment: prod (shelter_uat)

### To reproduce
1. Go to a subject type
2. Make a change in the subject summary rule
3. Save
4. Wait for some time and look at the individual table. All last_modified_date_time values are modified

Nothing except a change in sync attributes should lead to a change in all last_modified_date_times

**Comment by mahalakshme** [comment]
@vinayvenu Isnt this 7.1.0 release?

**Comment by mahalakshme** [comment]
@1t5j0y testing done. we can run in prod.

**Comment by 1t5j0y** [comment]
Executed in prod.

**Comment by 1t5j0y** [comment]
Added fixing of logic to check last job status to scope of this card
