### ISSUE TITLE
CSV update of addresses for subjects is not handled correctly

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#688]
### Need:
Recently around 30k individual's addresses were updated unaware of the existence of this issue and it led to chaos on the ground for the org and fixing it took atleast 40 man hours.

### Acceptance criteria:
Make sure when a address of an individual is updated via CSV:
- Make sure address of all related entities where denormalised - encounter, program encounter, enrolment, individual, entity approval status needs to be updated. Currently for encounter/program encounter address is not updated.
- subject migration entry need to be inserted. This is not happening now.

**Comment by AchalaBelokar** [comment]
- [ ] blocked because of this card https://github.com/avniproject/avni-webapp/issues/1162

**Comment by 1t5j0y** [comment]
@AchalaBelokar blocker fixed. Can retest this after deploy the server fix.

**Comment by AchalaBelokar** [comment]
- [x] Created individual  with csv 
- [x] fill the encounter
- [x] edited location of that individual 
- [x] see in the database

**Comment by mahalakshme** [comment]
@AchalaBelokar the above tests are not sufficient. You need not check in db. BTW what did you check in database?

Say u r changing the location from A to B,
- From a usecase perspective, you need to check if individual is moved out of user's catchments with location A alone
- And you get all entities mentioned in AC synced to the user with catchment with location B

**Comment by AchalaBelokar** [comment]
- [x] Tested with csv upload

**Comment by AchalaBelokar** [comment]
- [x] I changed the location via csv
- [x] created a one user

**Comment by mahalakshme** [comment]
@AchalaBelokar test cases are not detailed - it will be helpful if you can also add what did you test with the created user.
