### ISSUE TITLE
Get of encounters - external API is very slow

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#702]
### Issue:
On doing the below:
```
zgrep '/api/encounters' chs.log.2024-03-14.*
zgrep '/api/encounters' chs.log.2024-03-13.*
```
found the below logs:
taking 2 mins when page number is higher:

![Image](https://github.com/avniproject/avni-server/assets/10369963/8364781a-88d2-4037-844d-6266ef60d548)

Lesser time when page no is lower:
<img width="1512" alt="Screenshot 2024-03-18 at 12 12 26 PM" src="https://github.com/avniproject/avni-server/assets/10369963/d6b2e48d-91d8-4b42-b1ff-72d7b33860e7">

But unable to reproduce the issue via POSTman: taking less than 40 secs even when page no is higher
![Image](https://github.com/avniproject/avni-server/assets/10369963/b5467902-0a6c-439a-a1b4-aea9f7a66593)

### AC:
- Identify rootcause of the issue
---- Is it because prod was slow around that time
---- similar to sync offset problem - higher page no contributing to slow sync - https://github.com/avniproject/avni-client/issues/524
---- or some issue in code - contributing to more response time - generally
---- or something else?
- What are the possible solutions for the above identified rootcause

**Comment by petmongrels** [comment]
### notes
- increasing page number is slowing the response to some extent
- using encounter type improves the response times significantly
- using page size is improving the response time (check for concept cache hits)

**Comment by AchalaBelokar** [comment]
- [ ] tested with rwbniti22
- [ ] tested with ai@gvam_uat mentioned in the sheet
- [ ] tested with maha@calcutta_kids
