### ISSUE TITLE
User update does not update audit information

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#706]
The regular audit mechanism for all transactions in Avni does not work with the ```User``` domain object. As a result, all changes require us to manually set the user who updates a user. This currently does not happen for the following. 

1. PUT /user/{id}
2. DELETE /user/{id}
3. PUT /user/{id}/disable
4. PUT /user/accountOrgAdmin/{id}/disable

There is a ```User.setAuditInfo``` that will need to be called in all these scenarios

**Comment by vinayvenu** [comment]
@Dashlet26 didn't understand your concern.

**Comment by Dashlet26** [comment]
Whats the issue in this

**Comment by vinayvenu** [comment]
Try any of the urls mentioned in the issue, and you will notice that last_modified_by_id and last_modified_by columns on the users table are not modified. They need to be updated in all these scenarios. 

If this is not clear, please join https://join.skype.com/xiTU162DSJTd so we can understand your concern.

**Comment by MiirzaBaig** [comment]
@vinayvenu Would like to work on this bug, if needed we can join a call for understanding the bug in depth...

**Comment by ombhardwajj** [comment]
@vinayvenu , I've tried to fix this issue . Could you please review the changes? Please let me know If any further adjustments are needed!!

https://github.com/ombhardwajj/avni-server/commit/64df2659901b03bae7de4ca0c2ebc63e109b31a6

**Comment by vinayvenu** [comment]
@ombhardwajj can you please raise a PR?

**Comment by AchalaBelokar** [comment]
- [ ] checked edit
- [ ] checked with disable user
- [ ] edit user with same user
- [ ] change the catchment
