### ISSUE TITLE
Subject type not available in /api/subjects

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#712]
The value of "Subject type" is available only when it is requested in the url, and not present when it is not requested in the url. 

eg: 

Request ```https://app.rwb.avniproject.org/api/subjects?subjectType=Farmer```
Response 
```
{
    "content": [
        {
            "Subject type": "Farmer",
            "ID": "a6caa3d2-3d95-45c7-b439-15dc0a59467e",
...
```

Request ```https://app.rwb.avniproject.org/api/subjects```
Response 
```
{
    "content": [
        {
            ~~"Subject type": "Farmer",~~
            "ID": "a6caa3d2-3d95-45c7-b439-15dc0a59467e",
...
```

**Comment by himeshr** [comment]
This change could cause issues for other External API consumers, as they might rely on the field to determine the subjectType amongst the returned entities.

If a change is to be done, i would recommend retaining the subjectType Name details always irrespective of "subjectType=<name>" filter being specified.

**Comment by vinayvenu** [comment]
@himeshr this was a recent break in functionality caused by a merge. I doubt if any existing consumers will be affected by it.
