### ISSUE TITLE
[External API][Performance] Make retrieving catchment optional

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#718]
GET /api/subject/#id takes up about 16% of the resources on the common cloud, and is slow (median response time 3.3 seconds). More than 90% of the time and resources are taken up because we are trying to retrieve all catchments the subject belongs to. Making this configurable can make the API at least 10 times more efficient. Overall improvement in Avni performance will be is around 14%. 

### Acceptance criteria
- Add a parameter "includeCatchments" (values true, false) to the GET api/subject/#id api. 
- By default, do not fetch the "catchments" field if this is not set to true

<img width="404" alt="image" src="https://github.com/avniproject/avni-server/assets/344222/dfa136f8-f5ac-4484-828b-f620f6942cff">
<img width="1310" alt="image" src="https://github.com/avniproject/avni-server/assets/344222/f2fa697f-1a86-4071-85f3-ebb6a35a5698">

**Comment by petmongrels** [comment]
Introducing a breaking/forcing change by making the includeCatchments = false. So that only people who require catchment pass it explicitly. Making it true will mean we not get performance benefit unless people make change.

**Comment by vinayvenu** [comment]
Context, as far as we know catchments are used only for the Bahmni HWC integration. Not sure if it is still being used after the pilot.
