### ISSUE TITLE
Location CSV Upload to update location properties fails with UniqueConstraint exception

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#720]
**Describe the bug**
Bug discovered as part of [this](https://avni.freshdesk.com/a/tickets/3897) ticket.
When user attempts to perform Location CSV Upload to update location properties, in-case the update location addressLevel's parent's name is not unique for that addressLevelType in the organisation, then the upload of that entry fails with UniqueConstraint exception.

Exception message:
org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2

**To Reproduce**
1. Create/upload Locations such that the last but one addressLevelType from the bottom has 2 different addressLevels with same title but different lineages.
2. Attempt to update properties for any of the children of the above parent addressLevel using "Create+edit" mode
3. Upload fails with "NonUniqueResultException" exception

Refer [this](https://avni.freshdesk.com/a/tickets/3897) ticket for error case.

**Expected behavior**
Location CSV Upload to update location properties is successul even when addressLevel's parent's name is not unique for that addressLevelType in the organisation

**Additional Information**
[ErrorStackTrace-3897.txt](https://github.com/avniproject/avni-server/files/15160354/ErrorStackTrace-3897.txt)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
Our system should never allow anything related to dealing with multiple locations with the same name. Remember we handled this. So throwing the above error related to it is fine. Anything to realise the already existing duplicate locations with same name!
