### ISSUE TITLE
Issues in retrieving approval status

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#723]
### Issue:
Some ACs [here](https://github.com/avniproject/avni-product/issues/1576) not met
- When entityType not passed fails like shown below:
<img width="1069" alt="api_issue" src="https://github.com/avniproject/avni-server/assets/10369963/ed199d7a-8dda-48d5-a513-a3188f5a5973">

- API [here](https://editor.swagger.io/?url=https://raw.githubusercontent.com/avniproject/avni-server/7.3/avni-server-api/src/main/resources/api/external-api.yaml) is incorrect 
        - URL mentioned incorrect, 
        - example of entityTypeId incorrect
        - mention the allowed values for entityType

### AC:
Fix the above

**Comment by himeshr** [comment]
Dev testing screenshots:
<img width="1840" alt="Screenshot 2024-05-03 at 3 25 36 PM" src="https://github.com/avniproject/avni-server/assets/72493481/b74d2733-0c9d-4b8a-98cb-cc592651a2c3">
<img width="1840" alt="Screenshot 2024-05-03 at 3 26 28 PM" src="https://github.com/avniproject/avni-server/assets/72493481/57ea951f-a839-4ae2-abdd-98b859165e80">
