### ISSUE TITLE
Case insensitive location matching

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#724]
https://avni.freshdesk.com/a/tickets/3751
https://avni.freshdesk.com/a/tickets/3897

### Issue:
Frequently same location with different cases are uploaded leading to duplicate locations and corrupted data(individuals registered in both locations). This in turn causes issues when updating locations, say when trying to update location properties via CSV since multiple locations with same parent would exist.

<img width="1510" alt="Screenshot 2024-05-03 at 9 08 40 AM" src="https://github.com/avniproject/avni-client/assets/10369963/db6d1d8b-ea95-4cd8-a3c0-80e99d5806ca">

### AC:
- In the webapp Admin tab, when creating a location, when a same location exist with different case and in the same location hierarchy, show error in the field as 'This location already created as part of the mentioned larger location' in red color in place of 'This field is required' in the below screenshot. The typed location name need to be retained when showing the error. The snackbar message at the bottom need not be shown.

<img width="1510" alt="Screenshot 2024-05-03 at 9 19 26 AM" src="https://github.com/avniproject/avni-client/assets/10369963/c29800d7-50ba-4f18-bc8e-b21fba738886">

- But if the same existing location name created as part of different location hierarchy it should be allowed.
- Via CSV upload as well, the above needs to work by showing the error for the corresponding location in the 'error' column in the error file that will get downloaded.

**Comment by 1t5j0y** [comment]
- Fixed for create/update via webapp.
- Leveraging existing server side error display mechanism (via toast message) and not changing it for this card.
- Location create via CSV upload already looks for existing address level titles ignoring case and treats it as an update of the existing record scenario if a match is found i.e. does not create a new location entry and does not throw an error.

**Comment by mahalakshme** [comment]
@1t5j0y can you share some screenshot of the error message. Mentioned the AC for error message so, since it was also the way how it was handled currently. You mean we will be showing the toast in the screenshot along with the error message in the field? If so, that is fine. If not kindly share screenshot.

**Comment by 1t5j0y** [comment]
@mahalakshme here you go 
![image](https://github.com/avniproject/avni-server/assets/54208632/9560f09d-fd22-4197-8cba-17a0660bcc33)

**Comment by mahalakshme** [comment]
@1t5j0y found the below issue:
- What I meant by this ```But if the same existing location name created as part of different location hierarchy it should be allowed.``` is that there are valid cases where two villages of same name can exist - when it is part of different taluka/block/state. Hence for such cases we should not show error. That is why mentioned this as error message "This location already created as part of the mentioned larger location". 
- Since toast disappears within sometime, I preferred mentioning error messages close to fields since I saw it working in some cases. But if it is more work, then the current behavior of showing error messages is fine.

**Comment by mahalakshme** [comment]
@1t5j0y To prevent such misunderstandings, I am fine in sharing the context of all cards before being picked up. But this requirement came in as urgent only yesterday and I have heard concerns when I explain the cards esp., on days other than Mondays. So not sure what I could have done.

**Comment by mahalakshme** [comment]
Joy mentioned the above is handled

**Comment by AchalaBelokar** [comment]
- [ ] Uttar Pradesh as state present in rwbmh on satging I entered a Uttar pradesh it doesn’t allow me, uttar pradesh it doesn’t allow me  uttarpradesh it allow me
- [ ]

**Comment by AchalaBelokar** [comment]
- [ ] Edit location is case sensitive it don’t allow if any thing which is case is upper

**Comment by mahalakshme** [comment]
@AchalaBelokar found it is working fine, in rwb staging. tested with below 2. only issue is that for Edit+create it expects parent locations to be of same case - which can be fixed later(as part of this card - need not be blocker for release), since it will not lead to corrupted data

[edit_location_edit_rwb_2 copy.csv](https://github.com/avniproject/avni-server/files/15245602/edit_location_edit_rwb_2.copy.csv)
[edit_location_edit_rwb_2.csv](https://github.com/avniproject/avni-server/files/15245604/edit_location_edit_rwb_2.csv)
