### ISSUE TITLE
Being able to identify media not uploaded

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#730]
https://avni.freshdesk.com/a/tickets/3932

### Need:
As part of this [card](https://github.com/avniproject/avni-client/issues/1156), we fixed the issue with media upload from mobile app, where observations are replaced with media url though image upload was failing. For such failed media uploads, we do not have a way to identify what media is missing in s3. Examples of such subjects are present in the ticket.

### AC:
The objective of this spike card is to find the tech tasks to do the below and to decide on the inputs received during the discussion:
- Given an organisation, scan all forms for media(image, audio, video) concepts
- For all such media concept observations(including voided entities), check if there is an entry in s3
- If not present, then write the info(table_name, id of the entry, media url in the observation) to a table or file. Eg: `individual, 1429414, https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/09985727-516b-40c8-b2ae-1beb07541a24.jpg`
- Also determine missing thumbnails images for whom the media images present in s3 

### Inputs:
- feed type of api
- table, after_time
- enable/disable
- can do quartz?
- out of scope: thumbnail? lambda needed? - one job, not trying again - lambda, too many things to monitor for one job, etl - java/node service

**Comment by 1t5j0y** [comment]
https://docs.google.com/document/d/1vVG88kgcKg9Q-Y1nCiQFWoDpjfzkc6rnk2nI2PttnIA/edit
