### ISSUE TITLE
Integration with Metabase [DMP 2024]

### ISSUE THREAD

**Issue by ombhardwajj** [avniproject/avni-server#733]
A POST API will be created to setup Metabase automatically for all the organisations in Avni

**Acceptance Criteria**
The API should
1)Setup DB connection
2)Create a collection
3)Create a group with access to DB connection and collection

#https://github.com/avniproject/avni-product/issues/1562

**Comment by petmongrels** [comment]
@ombhardwajj where can I find the commits

**Comment by ombhardwajj** [comment]
@petmongrels 
Here are the commits
https://github.com/avniproject/avni-server/pull/734/commits
I will push the latest ones soon!

**Comment by vinayvenu** [comment]
Added some comments.
