### ISSUE TITLE
Queries to fix duplicate privileges

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#746]
https://avni.freshdesk.com/a/tickets/4053

### AC:
- For Mobile Creches and Shelter [here](https://docs.google.com/spreadsheets/d/19ploiok119bivybM6Oc8ZB5S3SHgmcSTm5EFGHXF1Qk/edit?gid=82123690#gid=82123690) - encounter type, not included(include it). Update last_modified_by_user_id to your super_admin. And review other queries if they are fine.
- Across all orgs, wherever there is duplicate group_privilege which are **not voided and have same values for "allow"**, 
    - make an update to void all except one, 
    - for each of the entries to be voided, update the last_modified_date and last_modified_by_id and  set "allow" to false
- Add query to void all the duplicates and also set the "allow" field to "False" always for all voided groupPrivilges [ Note: Change as per details specified [here](https://github.com/avniproject/avni-client/issues/1459#issuecomment-2219993498)]
- ~Add query to update the impl_version of all voided(independent of allow is true or false) to 0 and non-voided to 1~

**Comment by himeshr** [comment]
> * Add query to update the version of all voided(independent of allow is true or false) to 0 and non-voided to 1

@mahalakshme Will not do this part as per discussion in Avni product group

**Comment by himeshr** [comment]
> @himeshr no Joy mentioned so, because of AC for his card. It will all work together correctly

As per discussion, will update impl_version instead of earlier mentioned version column in group_privilege table.

Depends on #721

**Comment by himeshr** [comment]
[templateExpressionToGenerateUpdateScript.txt](https://github.com/user-attachments/files/16142535/templateExpressionToGenerateUpdateScript.txt)

Used this to auto-generate the sql script for all org-sheets mentioned in this card's description.  [update script sheet](https://docs.google.com/spreadsheets/d/19ploiok119bivybM6Oc8ZB5S3SHgmcSTm5EFGHXF1Qk/edit?gid=82123690#gid=82123690)

**Comment by himeshr** [comment]
> the manually run script (created via this card) should only update is_voided (and get the db to a valid state where we can apply the constraint). Updating impl_version also here creates a circular dependency.
> 
> the migration (in #721) will introduce the new impl_version column, mark all voided rows with impl_version 0 and add the constraint.

Updated the script to not set the impl_version, and just retain 1 non-voided entry as part of the update script.

**Comment by himeshr** [comment]
Local testing on pre-release for "Mobile Creches" org was successful, with following sql commands executed and output recieved.
[sqlOutputMobileCrechesRemovalOfDuplicatePrivileges.txt](https://github.com/user-attachments/files/16176184/sqlOutputMobileCrechesRemovalOfDuplicatePrivileges.txt)
[mobileCrechesRemovalOfDuplicatePrivileges.txt](https://github.com/user-attachments/files/16176185/mobileCrechesRemovalOfDuplicatePrivileges.txt)

**Comment by petmongrels** [comment]
### For QA
- the scripts will need to be run on production
- testing and verification should be done in prerelease environment. When verifying we should verify whether the privileges for users are same as they are in production. This is required because the privileges will get updated when the deployment is done for this.
- It would be good to refresh pre-release before testing this (we should make sure that the downtime doesn't block other people)

**Comment by mahalakshme** [comment]
@himeshr 

- I have updated the privileges with discrepancies for all active organisations [here](https://docs.google.com/spreadsheets/d/19ploiok119bivybM6Oc8ZB5S3SHgmcSTm5EFGHXF1Qk/edit?gid=721645745#gid=721645745) in the sheet: 'For all active orgs with discrepancies'.
- The privileges with discrepancies have changed. So I have used the same formula in the above sheet. But you might need to find the duplicates with discrepancies once before running in prod to make sure there are no new discrepancies. 
- In the 'Active orgs' sheet have added the final list of active orgs that have discrepancies.

**Comment by himeshr** [comment]
Migration script available [here](https://github.com/avniproject/data-fixes/blob/main/all/voidAndDisallowDuplicateGroupPrivileges/voidAndDisallowDuplicateGroupPrivileges.md)

**Comment by himeshr** [comment]
Executed the group privileges updation [script](https://github.com/avniproject/data-fixes/blob/main/all/voidAndDisallowDuplicateGroupPrivileges/voidAndDisallowDuplicateGroupPrivileges.md) in production.
[ProdSqlsLogs.txt](https://github.com/user-attachments/files/16329449/ProdSqlsLogs.txt)
[ProdSqlsExecuted.txt](https://github.com/user-attachments/files/16329450/ProdSqlsExecuted.txt)
