### ISSUE TITLE
[Dashboard] Create default custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#749]
### AC:
On creating a new organisation,
- store a default custom dashboard with name(Default dashboard) with MyDashboard report cards within the dashboard sections and names like in MyDashboard. For 'Last 24 hours' report card, recent filters need to be selected. 
- In the Everyone group, mark it as primary dashboard
- 'Primary dashboard' configuration in custom user groups will override the configuration in 'Everyone' group
- The colour of the report cards need to be set to the hardcoded colours now - Scheduled - green(#388e3c), Overdue - red, other cards in white
- Add 'As on date' and 'Subject type' as filters of the default custom dashboard.
- Do not delete MyDashboardFilters in db and UI. It will be removed in the next release once this is stabilised and they are need for testing. 
- The default custom dashboard and report cards should be editable/deletable like any other custom dashboard
- Any missing steps from the above to achieve configuration of MyDashboard via CustomDashboard 
- Expose the above functionality via API, to handle creation of default custom dashboard for the existing organisations. API should input organisation id and return status code(success or failure for the organisation).
      - Add readme documentation with steps/strategy and do's/dont's to guide the support team to handle creation of default custom dashboard for existing organisations and to manually create the filters
      - Should be able to execute the API only on an org whose category is UAT
      - In some orgs already, default report cards are added to a custom dashboard. Eg: in JSCS, 'Lab Facility' user group users, use a custom dashboard to which some default report cards are added. Other user groups have default dashboard, as the primary dashboard. To deal with such cases, add the already existing report card to the default custom dashboard(when the name of the report card and the standard_report_card_type_id matches) to avoid confusions since it is not possible to create a report card with same name from the UI.
- Should be backward compatible, - meaning should work with old apk

### Tech inputs:
- The above migration to be done, by having an endpoint and not SQL migration. Feel free to change it.

### Few points on testing:
- Use the endpoint to migrate the MyDashboard in the relevant orgs and make sure it works. Update the prerelease db to be inline with the prod for the same if needed.
- On upgrading an app in older version, the old cached filters and counts(on disabling dashboard autorefresh) for users in mobile app UI, should not cause failure
- Some of the Shelter and JSSCP users have 'disableAutoRefresh' set to true
- Configuration to not show Total when any program selected.
- bundle import and update of default dashboard and report cards. And also bundle import/export when a default report card added to a custom dashboard

### To communicate:
- Mydashboard filters used by 6 orgs. So not much manual work.
- will be deprecated after stabilised
- support/implementation to do it for : 'Shelter UAT' and 'Adoloscent Sewa Rural UAT'
- Cached filters and counts of MyDashboard will not be retained.
- Default custom dashboard will appear in the More menu -> Dashboards

**Comment by 1t5j0y** [comment]
Approach modified for existing orgs - bundle upload will be used to create default dashboard. Steps documented on readme (not published) - https://dash.readme.com/project/avni/v2.0/docs/move-org-to-custom-dashboard-from-mydashboard

**Comment by Dinesh2019** [comment]
- [ ] when we are clicking filter option in the home page getting the below error : 

Property 'Text' doesn't exist
at render (address at index.android.bundle:1:4258062)
at finishClassComponent (address at index.android.bundle:1:367544)
at updateClassComponent (address at index.android.bundle:1:367405)
at beginWork$1 (address at index.android.bundle:1:399723)
at performUnitOfWork (address at index.android.bundle:1:386774)
at workLoopSync (address at index.android.bundle:1:386676)
at renderRootSync (address at index.android.bundle:1:386560)
at performSyncWorkOnRoot (address at index.android.bundle:1:384043)
at flushSyncCallbacks (address at index.android.bundle:1:349073)
at batchedUpdatesImpl (address at index.android.bundle:1:400497)
at batchedUpdates (address at index.android.bundle:1:341930)
at _receiveRootNodeIDEvent (address at index.android.bundle:1:342203)
at receiveTouches (address at index.android.bundle:1:395353)
at apply ((native)::)
at __callFunction (address at index.android.bundle:1:98035)
at anonymous (address at index.android.bundle:1:96528)
at __guard (address at index.android.bundle:1:97468)
at callFunctionReturnFlushedQueue (address at index.android.bundle:1:96486)



https://github.com/user-attachments/assets/e2ed5608-70a2-41e1-96f3-265f3d625ab7

- [ ] Can we have header for the card like the old UI so that user can have the clear idea

**Comment by 1t5j0y** [comment]
Fixes for issues reported 
- Client fix (unrelated to this story) [commit](https://github.com/avniproject/avni-client/commit/1f7335274de0b7795c61c9430f285e76248e19f3)
- Changed dashboard view type to 'Tile'

Additional fixes
- Changed all default dashboard entities to use fixed uuids to avoid creation of duplicates via bundle upload

**Comment by Dinesh2019** [comment]
- [ ] when we upload the bundle the dashboard get added twice 



![Image](https://github.com/user-attachments/assets/c0a16095-828a-49c7-b9db-1616598b9e2e)

- [ ] In the old apk version 8.1.3 if we click on the filter app is getting crashed and also the count is not displayed for some card 



![Image](https://github.com/user-attachments/assets/41776618-026f-45e6-83a3-41a078cd4239)


- [ ] can we have header for the cards like old default dashboard 

old view : 



![Image](https://github.com/user-attachments/assets/c070def3-3126-4dcd-baf8-2d6305cbc398)


New view : 



![Image](https://github.com/user-attachments/assets/721b5b65-2475-45a8-8652-6777bd9211b2)

**Comment by 1t5j0y** [comment]
@Dinesh2019 as discussed please try with a fresh org as orgs created before the latest fix would have incorrect uuids for the different entities.

**Comment by 1t5j0y** [comment]
created avniproject/avni-server#781 for the issue on older apks.
Moving back to QA ready to retest the other cases with fresh orgs.

**Comment by mahalakshme** [comment]
@1t5j0y uploaded the bundle from readme to shelter org in staging environment. It is showing error file. On clicking error file, it shows oops page

![Image](https://github.com/user-attachments/assets/35f071f2-61cc-469b-9bfb-13c96ba56351)

Didn't create report cards or dashboard from the bundle.

**Comment by mahalakshme** [comment]
@1t5j0y also tried in Adoloscent Sewa Rural UAT in staging, got the below error file:

[errors-defaultdashboard.csv](https://github.com/user-attachments/files/16868447/errors-defaultdashboard.csv)

**Comment by 1t5j0y** [comment]
Moved back to original approach of using an API to create default dashboard for an org.
`POST /api/defaultDashboard/create?orgId=1234`

**Comment by AchalaBelokar** [comment]
1. I am not able to create default dashboard through the postman even though the user is admin user. I tried with 2,3 organisation like rwbnitiuat,jsscp,apfodisha
 ![Image](https://github.com/user-attachments/assets/cd6aa7a8-0ada-4271-a542-81d3138f3f78)

**Comment by 1t5j0y** [comment]
@AchalaBelokar need to use super admin user token
