### ISSUE TITLE
Unable to create super admin user

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#750]
Server is unable to determine region to validate the phone number.

**Comment by AchalaBelokar** [comment]
not able to create a super admin it is showing me communication error

**Comment by AchalaBelokar** [comment]
- [ ] try to create a user

**Comment by petmongrels** [comment]
large change in code hence moving it to code review

**Comment by Dinesh2019** [comment]
still getting the same error deployed latest master and tested it 


[Click here to watch video](https://drive.google.com/file/d/16BWUaI5zrpOWqeZ93Yyabtcu7dyjpAiV/view?usp=drive_link)

**Comment by Dinesh2019** [comment]
QA References : 

[Click here to watch video](https://drive.google.com/file/d/1B-j53303WpW2r3m5ZuXrbL_0jW5hjUi8/view?usp=drive_link)
