### ISSUE TITLE
Bundle issues with locations

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-server#751]
**Describe the bug**
When we upload a location using the bundle, the location properties are not updating; it only creates a new location.
**To Reproduce**
Create location with some properties in one org and download bundle with location  and upload it in other org, and check the location properties.

### AC:
- Should be able to bundle export and import, gpsCoordinates and locationProperties.

### Analysis points:
If foreign key reference has uuid instead of id? - need to refer to a unique value - so cant do this - anyways edge cases - so can handle as it comes

**Comment by himeshr** [comment]
Tested bundle dowload and upload for locations with gpsCoordinates and locationsProperties.
[RWB_2023_with_gps_and_loc_props.zip](https://github.com/user-attachments/files/16437053/RWB_2023_with_gps_and_loc_props.zip)
<img width="536" alt="Screenshot 2024-07-31 at 11 47 04 AM" src="https://github.com/user-attachments/assets/1baff3d2-b622-419a-8399-4e3c1d228182">
