### ISSUE TITLE
Uploading user and catchments not working with voided entries

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-server#756]
### Describe the bug
I am not able to upload the user & catchment via CSV getting  error "query did not return a unique result" .

### Root cause:
In implementation there are 2 groups with same name and one is voided.
In the code, we're checking for groups by name, and it seems there are two groups with the same name, causing the code to break. check [here](https://github.com/avniproject/avni-server/blob/a45c1d8b78d6df1c3c38e88d1ae40697c61e4d19/avni-server-api/src/main/java/org/avni/server/service/UserService.java#L145)

### Technical:
1. Update the code to consider only non-voided groups, catchment.

For address levels and sync concepts it is working currently since we rename the name on voiding.

voided or fetching

### Analysis points(Ignore):
- https://github.com/avniproject/avni-webapp/issues/1209 - Why do we change the name when something is voided - it is for the users to know and hence it is applicable only for transactional data and not for metadata, since we dont show the voided metadata anywhere right? Also changing the name will require migration for existing data.
- Too many cases to handle because of voided data(bundle upload etc.,) - Why cant we hard delete metadata?
- Or should we just rename and run migrations so that we need not handle at mutiple places 
- or handle at repository level in all places?

**Comment by mahalakshme** [comment]
will be fixed as part of https://github.com/avniproject/avni-webapp/issues/858
