### ISSUE TITLE
Add organisation categories and status

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#759]
### AC:
- For a super admin, when clicking 'SHOW' on an organisation, add Trial to the Category list. 
- Order of the listing in the Category field is Prototype, Trial, UAT, Production and Temporary.
- Add another dropdown called Status(add Live, Archived as the values) below the Category field.

**Comment by petmongrels** [comment]
### AC
- Alphabetical listing of category
- Default value of status = Live

**Comment by Dinesh2019** [comment]
QA Refer video : 

[Click here for video](https://drive.google.com/file/d/1_opyx318mgp5eBHdWVA3CD0qo4HnPXqe/view?usp=drive_link)
