### ISSUE TITLE
Incorrect lineage after updating location in WebApp

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/avni-server#761]
**Describe the bug**
Tried fixing the issue mentioned in https://github.com/avniproject/avni-server/issues/760 via web app.
Consider locations State V, District W, Taluka X, Dam Z (Missing GP/Village Y)
When updating a child location (Z) to a new parent (Y), expecting the lineage to be V.W.X.Y.Z, the result is V.W.Y.Z, with X missing from the lineage.

**Example:**
```sql
-- 982906 State A
-- 982907 District B
-- 982908 Taluka C
-- 982909 Dam E
-- 982910 GP/Village D
SELECT * FROM address_level al WHERE id = 974954;
```
Initial lineage in the database:
Before updating gp/village: `982906.982907.982908.982909`
After updating the dam's parent using the web app: `982906.982907.982910.982909`
The taluk level (982908) is missing from the lineage.

**To Reproduce**
1. Check the issue described in #760.
2. In the web app, create a new location (Y) with parent X.
3. Update the child location (Z) to have the new parent Y.
4. Check the lineage in the address_level table.

**Expected behavior**
The lineage should be updated correctly to V.W.X.Y.Z.
That is `982906.982907.982908.982910.982909`

**Additional context**

- The location_location_mapping table works fine.
- The ETL address table is also fine.
- The only issue is with the lineage in the address_level table.

Result of ETL after updating the location via the web app:
![image](https://github.com/user-attachments/assets/0269c837-6966-4619-bdba-880afcf32e9c)

**Comment by mahalakshme** [comment]
Root cause of above issue in itself will not happen anymore because parent locations are mandatory to be mentioned: dealt as part of https://github.com/avniproject/avni-server/issues/760
