### ISSUE TITLE
Error on assinging identifiers to users

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-server#768]
**Describe the bug**
Error on assinging identifiers to users

**To Reproduce**
1. Go to the Admin app
2. Click on the identifier assignment and click on create

**Expected behavior**
Error should not appear and it should allow the user to select users from the list

**Screenshots**

![Image](https://github.com/user-attachments/assets/d0879024-5b12-4c44-b61a-91471223de83)

**Comment by himeshr** [comment]
## Test cases for QA of IdentifierUserAssignment CRUD on webapp

## Success
- View of identifierUserAssignment is working as expected
- Create of new identifierUserAssignment with valid values was successful
- Create of new identifierUserAssignment with already used values fails as expected with appropriate error message
- Deletion is allowed and works as expected

## Failures
- Edit of existing identifierUserAssignment with valid new values shows error on screen but succeeds intrernally, as seen in attached video
- Edit of identifierUserAssignment with invalid values shows error but again succeeds intrernally

https://drive.google.com/file/d/1aBHC6f-uQJ5EEv2qJzBt4HBJPU2Ct8sj/view?usp=sharing

**Comment by himeshr** [comment]
> ## Failures
> * Edit of existing identifierUserAssignment with valid new values shows error on screen but succeeds intrernally, as seen in attached video
> * Edit of identifierUserAssignment with invalid values shows error but again succeeds intrernally
> 

Validated that afore-mentioned test cases now work as expected.

**Comment by Gojo-Taqi** [comment]
@mahalakshme The issue still persists.
Please look at it.

The issue occurs when you try to assign identifiers from user assignment.

**Comment by Gojo-Taqi** [comment]
@mahalakshme I made a mistake, the fix is not yet deployed in production.
You can ignore my older comment.
