### ISSUE TITLE
Bundle upload issues

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-server#770]
Env: Staging
Bundle source Org: APF
Uploaded bundle to: apf2
Attempt1: [Bundle](https://drive.google.com/file/d/1Rp80vUGhvOO5Dx__xfrxvINOYu6eCiUO/view?usp=drive_link), [Error](https://drive.google.com/file/d/1UKK9qSOZ8oAcVHZwvgg-YjIUdMrZqP2w/view?usp=drive_link)
Attempt2: [Bundle](https://drive.google.com/file/d/1U8poqFRNEw53QfKJV_73_s0U30IsiIA3/view?usp=drive_link), [Error](https://drive.google.com/file/d/1qqhUL3bobSs2CHgYdpK39Hn9dmec5NUY/view?usp=drive_link)

Issues:
1. Attempt1 error file has several errors around transactions
2. Attempt2 error file has 2 errors
- locations.json - "Location with same name... exists" but no conflicting location exists in apf2 in the db. The exported bundle has a conflicting location with the same name/level.
- catchments.json "AddressLevel with uuid not found" but addresslevel exists in locations.json. The addresslevel uuid is different from the one that failed in the previous error.
3. After attempt1/attempt2 none of the locations or catchments in the bundle were available in apf2.

**Comment by AchalaBelokar** [comment]
- [ ] Downloaded a latest bundle and upload that testachapf org ... uploading time is
