### ISSUE TITLE
Optimise this report query

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#775]
### Issue:
[This](https://docs.google.com/document/d/1dDi9JRJHPkMhxklasOBz_5w2_PCrdZPuDwx5KuGe3rw/edit) query, going to be used on superset reports for APF org, is very slow - takes 37 secs when load on prodread db is low

#### Done using `explain analyse`
1. Replacing 
`c.base_date::DATE + ((cicv.item_detail_status::JSON ->> 0)::JSON ->> 'end')::INT AS due_date`, with 
`c.base_date::DATE + cicv.item_detail_end/(86400) AS due_date`, 
saves 15 secs since we are avoiding JSON parsing.
2. Adding index on ETL address tables on id column - might help since nested loop join is done between ETL address and public.individual table
3. To check if the slowness caused by join with `checklist_item_checklist_view` can be minimised, dumped the data of view into `apf_temp_from_view` table in prerelease, created an index on it and used this table instead of the view. But found it to be slow. Further analysis here can be made.

### AC:
- Identify all hotspots and suggest ways to optimise
- Is creating ETL tables for checklist related querying, is worth the effort? 
- Add the optimised query [here](https://docs.google.com/document/d/1dDi9JRJHPkMhxklasOBz_5w2_PCrdZPuDwx5KuGe3rw/edit#bookmark=id.pc6ycegfxld1)

### Out of scope:
Correcting the logic of the query which is incorrect

**Comment by himeshr** [comment]
Updated the optimised query [here](https://docs.google.com/document/d/1dDi9JRJHPkMhxklasOBz_5w2_PCrdZPuDwx5KuGe3rw/edit#bookmark=id.pc6ycegfxld1)

Query Plan is available here for reference
https://explain.dalibo.com/plan/d705hf8faae4893f

**Comment by himeshr** [comment]
Sample org Address Table schema before and after ETL run to create index for Address "ID" columns
<img width="742" alt="Screenshot 2024-08-27 at 3 25 23 PM" src="https://github.com/user-attachments/assets/cf3db689-15b6-48e3-9c52-99c7415ce04c">

**Comment by himeshr** [comment]
If needed, implementation team can manually create index for their target organisation address.id column using command
```
set role <db_schema>;
create unique index concurrently address_id_idx on address (id);
```

**Comment by AchalaBelokar** [comment]
As per discussion with @himeshr no need to QA this card.
