### ISSUE TITLE
[DEA] Enhance Sync attribute settings

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#779]
### Need:
When there are many sync attribute values added as on need basis, it is difficult to update the users with the new sync attributes, especially when full access need to be given on DEA.

### AC:
- Have a toggle that says 'Do not restrict on Data Entry App'.
- Default value for it is false
- When enabled, then don't apply the sync attribute restriction on DEA alone

#### User settings on Edit:
<img width="1006" alt="Screenshot 2024-08-29 at 11 35 23 AM" src="https://github.com/user-attachments/assets/ebda82d9-3c37-4e9d-8141-25797c17c760">

#### User settings on Show:
<img width="872" alt="Screenshot 2024-08-29 at 11 35 32 AM" src="https://github.com/user-attachments/assets/7651f577-9ad8-4d91-a38c-5671f6fdcafc">

### AC:
- When sync attribute value is 'any' for text and numeric concepts in the User page, then do not apply the 'sync attribute' restriction and should sync based on whatever other sync strategies are configured.
- Not applicable for coded concepts
- Only applicable for text and numeric fields
- Should work(sync) the same in mobile app as well
- Default value is 'any' for text and numeric
- Even if one of the values is 'any' then do not apply the sync attribute restriction

#### Why not mentioning any value for sync attribute is not considered as sync everything?
- Generally users forgot to set the sync attribute or catchment - then everything will get synced and they will not realise that their sync configuration is incomplete
- For individual assignment and catchment, when not set, we don't sync anything - and that is reasonable inline with the need and what is intuitive
- To make it evident - when something not set as sync attribute - it is not evident that everything will be synced.

#### Why only applicable for text and numeric fields:
-  it for these types that values can be of wide range
- for coded we currently only show the configured answers - creating a default answer or allowing the user to type 'any' and error handling for these - all these will add unnecessary complexity

#### Can we set any for numeric field:
Yes, the way we store the value of sync attributes - it is allowed to be stored.

### Questions:
- Should we just consider {}(default value when no sync attribute set) as any field?
  - Sync attributes then should be mentioned only when needed to restrict, and other strategies are based on allowing
  - Not consistent with other strategies - but anyways it is a different strategy
  - How to make the above evident: rename it to 'Sync Restriction Settings'?
  - In mobile app as well, need to work like this
  - None of the active users have sync_settings empty, so not an issue

### Inputs:
- Mandatory -
- user sync settings -

**Comment by himeshr** [comment]
## Sample Screenshots for the User flag

<img width="491" alt="Screenshot 2024-08-29 at 6 24 06 PM" src="https://github.com/user-attachments/assets/a0182dad-a30c-4a6c-af04-d96fc2b8938f">
<img width="924" alt="Screenshot 2024-08-29 at 6 23 51 PM" src="https://github.com/user-attachments/assets/5f982f3e-b34f-44fc-aefd-bd9feda7f3f8">
<img width="870" alt="Screenshot 2024-08-29 at 6 23 41 PM" src="https://github.com/user-attachments/assets/53a1602f-1091-4b52-a1a4-f2c97b46b19e">

**Comment by AchalaBelokar** [comment]
- [ ] I tried with maha@goonj I change the sync concept inventory remove jaipur from but still I am not able to create inventory item.

**Comment by himeshr** [comment]
> * [ ]  I tried with maha@goonj I change the sync concept inventory remove jaipur from but still I am not able to create inventory item.
> * [ ]  I login the AchalaB@rwbnitiuat I change sync attribute year changed and checked dea it is showing all the year

- The first error scenario is valid, as the user maha@goonj only has Thane district in catchment test
- The second scenario is also valid, as view is allowed in DEA irrespective of catchment or sync settings per subjectType. Only Create, edit and void are restricted in DEA based on catchment and SyncSettings.

**Comment by AchalaBelokar** [comment]
- [ ] Login with maha@goonj and created inventory  item ass and  try to edit with Center / Field office goonj with Goonj Than it is showing me right message and after that I fill correct the Goonj  Thane it is not allow me to save that inventory item.

https://github.com/user-attachments/assets/3cc8fa18-d7de-4218-accf-c98db11710f9

**Comment by himeshr** [comment]
@AchalaBelokar this is again a valid error, during edit, User is allowed to modify the entity, only if the previous sync attribute was valid for that user. 
As specified in your comment, the previous value for sync attribute was "goonj", which is not valid for user maha@goonj as it needs it to be "Goonj Thane".

**Comment by himeshr** [comment]
@AchalaBelokar and @dinesh2096 i see that the card is now in QA Failed, if this was on purpose, specify the issue here.

**Comment by himeshr** [comment]
@dinesh2096 The errors and app behaviour seen in this video are all valid..
https://drive.google.com/file/d/1Mme0mjT-qHXjLNzHvANQiHp2PIveHAFn/view?usp=drive_link

During create, the new SyncAttribute value and location specified should match the user sync settings and catchment
During Edit, the previous value for the SyncAttribute and locations should match the user's catchment and sync settings
