### ISSUE TITLE
Default filters not to break in older version of client

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#782]
### Issue:
Currently when we make the custom default dashboard as the primary dashboard it will not work in older versions of mobile app since 'subject type' filter and 'as on date' filter were not supported before and the app is seen to crash like below:

![Image](https://github.com/user-attachments/assets/91ee56e9-cb99-4ea4-8fc2-7d5c43857702)

### AC:
- Do not sync 'default dashboard' and its marking as primary dashboard, in the current API used to fetch these info
- For 10.0 and future versions of app, create a new API which will sync the 'Default Dashboard' as well and its marking as primary dashboard as well. Keep what will be synced as part of this API as much minimum as possible so that in future we can merge the code easily.
- It should work for below scenario as well:
        - User user1 is in 9.4 of shelter
        - Shelter is migrated to use new default custom dashboard at time t
        - But user1 sees MyDashboard since he is in 9.4
        - Implementor adds new dashboard called 'Slums not audited' at time t+1
        - user1 gets 'Slums not audited' on sync
        - user1 updates the app to 10.0
        - user1 should get 'new default dashboard' added as the primary dashboard
- Any new filter, dashboard, report card, group dashboard created or modified after 09-09-2024 (this date can be changed) should not sync to the app if the version of the app is < 10.0.

**Comment by himeshr** [comment]
@petmongrels, Found 1 issue as of now during QA:
- After deploying 10.0 latest code on prerelease, 
- I had set the following property, ```export AVNI_ENDPOINT_END_OF_LIFE_1=2024-09-05```
- and restarted the backend server

Inspite of this, on first time sync of AchalaB@shelteruat user, i still received Custom Dashboards with names "Default Dashboard", 'htestdash' and 'htestdash2' which were created /updated on 09-sep-2024, which shouldn't be the case.


<img width="571" alt="Screenshot 2024-09-11 at 6 41 12 PM" src="https://github.com/user-attachments/assets/49b399f0-8322-494f-b55d-942cf7168e34">
<img width="1439" alt="Screenshot 2024-09-11 at 6 41 27 PM" src=
"https://github.com/user-attachments/assets/1a375255-3da6-4cf0-9830-b972c5873df7">
<img width="595" alt="Screenshot 2024-09-11 at 6 42 31 PM" src="https://github.com/user-attachments/assets/8321722d-ccff-49b4-8800-50f627509735">

**Comment by himeshr** [comment]
Its now Working as designed..
Pending tasks before deployment:
- Write up for implementation team on how to handle sync for new changes post EndOfLifeDate that do not use 10.0 features
- Configuring the EndOfLifeDate suitably on avni-server as part of infra

**Comment by mahalakshme** [comment]
Add documentation for workaround for backward compatibility issue(new report cards not working with old client) explaining the usecase in readme - under Implementors guide - somewhere linking this [guide](https://avni.readme.io/docs/offline-reports) - needed to communicate further with implementation team

**Comment by petmongrels** [comment]
appendix section -
https://github.com/avniproject/avni-product/releases
