### ISSUE TITLE
Add a check to see if database , collection and Permissionsgroup already exist when API to setup Metabase is hit [DMP 2024]

### ISSUE THREAD

**Issue by ombhardwajj** [avniproject/avni-server#786]
# What

Currently when the API is hit more than once , the code stops executing when it reaches metabase Group creation 
`Group metabaseGroup = groupPermissionsRepository.save(new Group(name));`
but duplicate database and collection will be created.
We need to stop this duplication.

# Acceptance Criteria:

- Make sure that database , collection and permissionsgroup are created if and only if they dont exist

Related Issue : avniproject/avni-product#1562

**Comment by petmongrels** [comment]
1) minor comment - an error log file has been commited. other than removing it, you may also put a .gitignore for it.
2) new ObjectMapper() - I cannot tell from this commit alone, but in the codebase there should be only one place where ObjectMapper should be instantiated. We have a singleton in avni-server for this already - please use that.

**Comment by ombhardwajj** [comment]
I've replaced  initialization of a new ObjectMapper with the ObjectMapperSingleton already present in avni-server  👍

**Comment by mahalakshme** [comment]
@himeshr QA can be done for this right? why it is moved to Done without QA?

**Comment by himeshr** [comment]
PR Merge auto-closed the Card.

> @himeshr QA can be done for this right? why it is moved to Done without QA?
