### ISSUE TITLE
Offline Dashboard Filters are not set in bundle upload

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-server#795]
**Describe the bug**
During goonj work I've uploaded bundle from prod to uat. Dashboard filter are not inserted as per prod.

**Server Version** 
9.4 - happens in 10.0 as well

**Screenshots**
prod:
<img width="1484" alt="Screenshot 2024-09-20 at 11 25 27 AM" src="https://github.com/user-attachments/assets/67f8b900-555e-4bb2-bd6b-0a4d791e6a1f">

uat:
<img width="1469" alt="Screenshot 2024-09-20 at 11 25 14 AM" src="https://github.com/user-attachments/assets/273fcdef-0a01-4fa2-b64a-8decdccf1370">

**Comment by mahalakshme** [comment]
@vedfordev test in 10.0 it should work

**Comment by vedfordev** [comment]
@mahalakshme I tried in prerelease with creating new org. it is not creating dashboard. check org **ved-dash**.
[errors-Goonj.csv](https://github.com/user-attachments/files/17072549/errors-Goonj.csv)

**Comment by mahalakshme** [comment]
@vedfordev it is not creating dashboard filters u mean?

**Comment by vedfordev** [comment]
@mahalakshme yes

**Comment by mahalakshme** [comment]
we have fixed this issue 2 times before - so moved this card to QA failed.

**Comment by mahalakshme** [comment]
fixed in 10.0 - between 10.0 orgs shud work
