### ISSUE TITLE
Issues with retrieving/caching addresses during sync

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#798]
### Need:
- On calling POST /syncDetails for syncing by catchment, we are retrieving all addresses of a catchment that takes more time
- Also we are caching the above retrieved addresses in cache which is bloating the cache memory

### Technical suggestions:
- using ltree of address_level table will be faster to retrieve addresses of a catchment, 
- no need to retrieve from virtual_catchment_address_mapping table, and might not need to cache as well if the above is fast enough
- But using ltree doesn't work with RLS, might need to do as openchs user

### AC:
- Check if using ltree makes it faster enough equivalent to using cache
- If so, remove using cache for this purpose.

**Comment by petmongrels** [comment]
We should introduce reset role in this case as the performance gain seems quite a lot.

https://explain.dalibo.com/plan/1ef87e3b4dd65c31
https://explain.dalibo.com/plan/d9d2be477gb8e2c5

**Comment by 1t5j0y** [comment]
Pending fixing the cache related tests introduced in #794 to run predictably.

**Comment by 1t5j0y** [comment]
QA Notes:
will have to test following flows to ensure there is no functional change:
- sync
- task assignment
- DEA save
- reset sync
