### ISSUE TITLE
Memory overload

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#799]
### Need:
- From a previous card it was found out that addresses in some big catchments have occupied so much memory causing CPU to spend most of its time in doing GC affecting the performance of other users.
- POST to /web/individuals taking 80 secs.

### Analysis:
- No mobile app sync was done for these users when the issue happened, To prevent it from being done in future, remove the sync attributes for the users with Master catchment. 
- Webapp POST to /web/individuals was done around the same time the issue happened.

### AC:
-  lineage column in address_level table and catchment_address_mapping table can be used to find if the user has access instead of using virtual_catchment_address_mapping table.
- For users dinesh@org, rahul@org, jelwin@org, athulya@org, where org is the organisation in focus, remove their sync attributes and enable the setting 'Ignore below listed Sync settings in the Data Entry app'. Add query as needed, so that it can be run after its review.

### Out of scope:
fixing other usages of virtual_catchment_address_mapping table

### AC:
	- Goonj restrict size
	- 1 min
	- 1/4th - object: CatchmentProjection
		○ SQL brings  - 
		○ Memory dump
		○ Server -
		○ 1.5 GB - stack - where the memory is held
		○ Change the way distributions are done - village can be location form field

**Comment by petmongrels** [comment]
### about ACs
1. it is already fixed by Joy in another story.
2. is not required to be done due to location check (as DEA performance is fixed by above and mobile endpoint is not in scope of this card).

**Comment by AchalaBelokar** [comment]
- [ ] search is not working on data entry app. Login with dinesh@adjnpct and created the individual with name ACH test and try to search it is not showing anything .but is present on data entry app.

**Comment by mahalakshme** [comment]
@AchalaBelokar where did you type the name - in 'Search All'? can u share a screenshot?
If it is so, the above is the expected behaviour, yes it is confusing for which there is a card.

**Comment by AchalaBelokar** [comment]
- [ ] Yes Maha In serach all text field I put the name![Image](https://github.com/user-attachments/assets/464541e3-c6a2-4554-b3bd-d64928b4f7d7)

**Comment by mahalakshme** [comment]
@AchalaBelokar then it is not a bug as of now - only observations in registration and enrolment are searched with whatever you type there. 

You can create a new name search field and then try the above, to work as expected.
