### ISSUE TITLE
Bundle upload with no changes and report card updates breaking fresh sync

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#801]
### Issue:
When some bundle upload made, - last_modified_date_time updated
or just report card alone updated, then on fresh sync users will face the above issue - Soln: pace up the release

### Steps to reproduce:
- Download bundle from an org: tried with JSCS and APF odisha
- note the last_modified_date_time of report cards
- upload the same bundle to the same org from where it was downloaded
- If you notice, the last_modified_date_time is updated from some of the report cards

### Need:
New/fresh sync users will face the error on sync: 'card are mandatory for DashboardSectionCardMapping, Keys being saved...' when a bundle from UAT to prod is uploaded

### Tech Analysis:
1) One reason is what we insert as standard_report_card_input in migration and what is inserted via bundle import is different
- {"programs": [], "subjectTypes": [], "encounterTypes": []} - via bundle import
- {} - via server migration

### AC:
**_- Do the changes in new release branch forked from 10.0.0 since 10.0.1 server testing will probably take more time_**
- Block report card saving via bundle upload and via web UI for production organisations. Should be able to save for UAT and other type of organisations.
- show message on UI and bundle upload CSV error file that: 'Cant save new changes to report card. Report card features under maintenance. Please try again after few days.'

**Comment by petmongrels** [comment]
1. Fix the existing database records to to use {"programs": [], "subjectTypes": [], "encounterTypes": []} instead of {}
2. Fix the last modified date time for report card to created date time value
3. The problem seems to be only in report card.

```select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_filter order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section_card_mapping order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from report_card order by last_modified_date_time desc;```

**Comment by mahalakshme** [comment]
@petmongrels yeah agreed - we cant avoid the last_modified_date_time update -I had added that as soln when I thought we are updating the last_modified_date_time for some reason, even when there are no changes, later realised the issue after tech analysis

**Comment by mahalakshme** [comment]
verified: production organisations are correctly marked as production in Category.

**Comment by himeshr** [comment]
Marking this card as 10.0 to be clear on where code changes are to be done, will use 10.0 branch offshot 10.0_hotfix for this.

**Comment by mahalakshme** [comment]
sure thanks @himeshr

**Comment by mahalakshme** [comment]
@himeshr dont know if reportDashboard.json will also update report card table in some cases - just sharing the scenarios that striked me.

**Comment by himeshr** [comment]
> @himeshr dont know if reportDashboard.json will also update report card table in some cases - just sharing the scenarios that striked me.

Have handled all locations from where cardRepository.save() is invoked.

**Comment by himeshr** [comment]
#### Sample Error Responses as required after fix done in this card:

[ReportCardBundleUploadError.csv](https://github.com/user-attachments/files/17305470/ReportCardBundleUploadError.csv)
<img width="1840" alt="Screenshot 2024-10-09 at 2 32 47 PM" src="https://github.com/user-attachments/assets/c81ebc2d-88d5-4bff-acf1-06ae5a8a27fc">
<img width="1840" alt="Screenshot 2024-10-09 at 2 31 16 PM" src="https://github.com/user-attachments/assets/5b4cf7d2-dd56-42a1-b19a-d23ec3dd66ad">

**Comment by himeshr** [comment]
Made additional changes to block Create/Update/Delete for CustomDashboard related entities listed below:
- Custom Dashboards
- DashboardFilter
- DashboardSections
- DashboardSectionCardMappings

**Comment by himeshr** [comment]
Currently, the only impact due to this issue is that Users Fresh Sync on old client will fail, in-case there is changes to reportCard and related entities after 26Sep2024.
To handle this change, the data fix needed is to update lastModifiedDateTime to a value before 26Sep2024.

Not going ahead with the blocking approach, as we are not able to clearly reason out impact points and issues that might arise out of this change. Instead, see the changes being done as part of #802 to mitigate occurence of this error and a action plan to handle all future such errors.
