### ISSUE TITLE
Instead of blocking report card saving in production, any other solutions?

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#802]
### AC:
- We have/gonna block the saving of report card. To avoid this blocking from being imposed for long time, explore any other possible technical fixes like posponding the EOL etc.,,
- After discussing with team we can decide on implementing.

**Comment by himeshr** [comment]
On discussion we found that the approach specified in #801 is not clean and could open up more issues than resolve.
Therefore, we have decided to take a fall-forward approach and do the following:
- Implement  metabase alerts, every 4 hours once, to identify report cards which were created before 26 Sep 2024 and modified after that date
- Make code change to fix issue with needless lastModifiedDateTime update for ReportCards when there is no change

For any further issues encountered during bundle upload or entity modifications, we'll follow a similar approach to fall forward through code fix and data migrations.

**Comment by himeshr** [comment]
#### Sample Error Responses as required after fix done in this card:

[ReportCardBundleUploadError.csv](https://github.com/user-attachments/files/17305470/ReportCardBundleUploadError.csv)
<img width="1840" alt="Screenshot 2024-10-09 at 2 32 47 PM" src="https://github.com/user-attachments/assets/c81ebc2d-88d5-4bff-acf1-06ae5a8a27fc">
<img width="1840" alt="Screenshot 2024-10-09 at 2 31 16 PM" src="https://github.com/user-attachments/assets/5b4cf7d2-dd56-42a1-b19a-d23ec3dd66ad">

**Comment by himeshr** [comment]
### Code fix done

 Code fix and DB migration done to update the existing database records to to use {"programs": [], "subjectTypes": [], "encounterTypes": []} instead of {} without updating the lastModifiedDateTime while ensuring we dont change the reportCards in-case there is no change.

### Metabase Alerts have been setup using below checks

```sql
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_filter order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section_card_mapping order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from report_card order by last_modified_date_time desc;
```
 
 ### Action need for Issue resolution 
 Fix the last modified date time for updated report cards (or other entities) to created date time value, if it is greater than our end of life date.

**Comment by mahalakshme** [comment]
@petmongrels one issue I see here is when we update the last_modified_date_time for an org, we need to keep track of it, so that next time when we need to update for the same org, it needs to be later than what was updated before

**Comment by mahalakshme** [comment]
@petmongrels may be not an issue, we can just keep track of minutes, independent of org, next day when we update, we can add some minutes and update

**Comment by 1t5j0y** [comment]
## QA
@AchalaBelokar 
- Deploy avni-server 10.0_hotfix_2 branch to prerelease - https://app.circleci.com/pipelines/github/avniproject/avni-server?branch=10.0_hotfix_2
- Check report card last modified date time for a few orgs
-- `set role <org_db_user>;`
-- `select * from report_card;`
- Download bundle for the org and upload it again to the same org. Repeat for few other orgs.
- Use the above queries to get the report card data again
- Verify last modified date time has not changed after bundle upload

**Comment by mahalakshme** [comment]
- the last_modified_date_time for report cards was for APF prod was updated to '2024-09-26 15:21:31.657 +00:00'
- So accordingly we can decide the last_modified_date_time - if we dont want to keep track last_modified_date_time for every org, then we can just add few minutes - randomise - so that same time not updated for all report cards and then update and then keep track of what is the highest last_modified_date_time got updated everyday.
