### ISSUE TITLE
[DEA] Search is slow

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#810]
https://avni.freshdesk.com/a/tickets/4778 and many more tickets

### AC:
- Search in DEA esp., concept answers, name, address, Search All are very slow Eg: in JSCS, search by SS takes around 2 mins
- Overall search in DEA in any way should not take more than 5 secs. If not possible to reduce than this, you can comment in the card.
- Search for subjects by name in the subject concept in the form in DEA also need to be within 5 secs.
- We can do a devbox for this, where after development, - me, QA and the developer can discuss to see if the improvement is satisfactory and to decide on the testing strategy.
![Image](https://github.com/user-attachments/assets/7bbd9626-5fe1-4166-a92a-0c2397598b1f)
- Also find the root-cause for the performance getting downgraded after 10.0.1: https://github.com/avniproject/avni-webapp/issues/1360#issuecomment-2422403006
- With respect to functionality, we can remove the sorting that happens by default during search, but users should continue to have a way to sort(in whatever columns now available) by clicking up/down arrow icon. All other features, w.r to functionality should continue to work like before

![Image](https://github.com/user-attachments/assets/3485b8cb-910d-46ce-a8e3-e4e3985f6214)

### Technical suggestions:
https://gist.github.com/petmongrels/353507f954ed0b31d434638ecacb90d0 

- Search in subject type concept in DEA forms, need not do count query
- Render count on DEA search results, on click of a button
- indexes on name - 
  ```
  Using pg_trgm , you can create a GiST or GIN index to speed up similarity search queries. This also helps regular expression-based searches, such as with LIKE and ILIKE operators.
  ```
- sort by first name not by all

### AC:
- Search by anything in Data Entry App should not take more than 5 secs(do not move the card to next lane without this criteria getting satisfied) - search by concept filters(JSCS, Goonj are good candidates), Search All, name, DOB, Address, Registration date filters, etc., - ie., all possible and combination of filters. 
- Validate the same using gatling performance setup since seems like the issue is raised now repeatedly for different reasons and also to make sure regression issues doesn't arise with respect to performance from our end. Add readme/steps for running the tests so that the tech tester can verify the same.
- The above also includes when searching by name for subject type concept. Currently(with the fixes made so far) this takes around 30secs the first time

### Technical suggestions:
- This is a suggestion made in the 1st card created. Why cant we just add a index on name fields - comment the reason for the same if not possible
- Search in subject type concept in DEA forms, need not do count query
- Search in DEA main search - displaying count is needed.
- Render count on click of a button
- indexes on name - 
  ```
  Using pg_trgm , you can create a GiST or GIN index to speed up similarity search queries. This also helps regular expression-based searches, such as with LIKE and ILIKE operators.
  ```
- sort by first name not by all

### Inputs:
- ETL - strategy pattern
- latest registrations/
- another db - Elastic search
- should not take more than one hour for any org
- name - ?
- Elastic search db
- postgres will bumping up resources help?

### Out of scope:
- removing sort, limited records ? - needs more analysis

some msg

**Comment by petmongrels** [comment]
https://avni.freshdesk.com/a/tickets/4778

**Comment by petmongrels** [comment]
https://gist.github.com/petmongrels/353507f954ed0b31d434638ecacb90d0

**Comment by mahalakshme** [comment]
I think by default we need not sort, but we can retain the sorting icon on the Name and whatever columns have it already, so that users can use it if needed.

![Image](https://github.com/user-attachments/assets/b7d4a6bf-43ea-4590-8105-8f5cd51a20b2)

**Comment by 1t5j0y** [comment]
#### Changes made:
1. Don't order search results by default. (Users can still sort by specific columns after getting search results.)
2. Use exists by query to eliminate use of distinct
3. Calculate count only for initial search. Pagination or sorting on a search result will use count already calculated for initial search.
4. Added logging to keep track of time taken by DEA searches (across results and count queries) for later analysis.

#### Observation:
- Count accounts for >90% of the time taken in several cases so getting rid of it or showing an approximate count will help a lot.


#### Areas for further investigation for improving performance:
1. Bumping up db memory does improve performance for queries using joins which indicates that there might be scope for db tuning on existing instance or that it is time to bump db resources if current performance improvement isn't sufficient.

-- 1.1. Resource bump performance for joins (rough indication based on manual checks)
JSCS coded concept search - db.t3.medium (1.83 minutes), db.t3.large (36.22s)
Note: With the current code change, this search now roughly takes 34s on db.t3.medium

-- 1.2. DB Tuning further reading and config recommendations
- https://pgtune.leopard.in.ua/?dbVersion=12&osType=linux&dbType=mixed&cpuNum=2&totalMemory=4&totalMemoryUnit=GB&connectionNum=100&hdType=ssd
- https://aws.amazon.com/blogs/database/determining-the-optimal-value-for-shared_buffers-using-the-pg_buffercache-extension-in-postgresql/

**Comment by 1t5j0y** [comment]
Removed calculation of count on server and display of count on webapp as agreed.
Concept and name searches for JSCS are well under 5 seconds now (tested against prerelease) .

**Comment by mahalakshme** [comment]
@petmongrels you are reviewing this no?

**Comment by AchalaBelokar** [comment]
- [ ] I login to AchalaB@jscs and search by ss it takes 1.7 as mention in the card it should be take more than 5 sec..

**Comment by mahalakshme** [comment]
@1t5j0y I am able to move beyond pages though there are none
![Image](https://github.com/user-attachments/assets/25168b37-85d8-4bf5-9887-d7fc6706968c)

![Image](https://github.com/user-attachments/assets/427d054b-9bc7-4a00-8720-6a34bbf7915a)

Also

**Comment by AchalaBelokar** [comment]
- [ ] I deployed server and serch for beta thal 1.5 min of AchalaB@jscs...this is happening for beta thal..  AA and ss it is working fine

**Comment by 1t5j0y** [comment]
Fixed the bugs raised.

Unable to simulate:
- Search selection not being retained on back from search results

Not fixed:
- Ordering of search: Search is by default unordered as specified in the AC of this card. User can choose to sort by clicking on the column header if required.
- Performance of search for rare observations (such as the 'Beta Thal' case above)
- Lahi alumni group registrations, enrolments has no data for search input 'megha' and hence no results is shown

**Comment by AchalaBelokar** [comment]
- [ ] Pls look at this video it is showing me the result 

https://github.com/user-attachments/assets/a69aba63-08cb-4d8a-8f3f-aacf01ef9727

**Comment by 1t5j0y** [comment]
> * [ ]  Pls look at this video it is showing me the result
> 
> 
> Screen.Recording.2024-12-02.at.8.43.22.AM.mov

'All text fields within observations of registration and enrolment' does not search by name of the subject. You can compare the behaviour against prod to confirm.
