### ISSUE TITLE
Release 10.0.4

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#811]
### AC:
- Release server alone - 10.0.4 branch

### Developer tasks:
- Release notes on product repo, 
- merging and tagging

**Comment by vedfordev** [comment]
release is done. developer task is pending.

**Comment by himeshr** [comment]
Release notes: https://github.com/avniproject/avni-product/releases/tag/v10.0.4
Merged 10.0.4 server into 10.1.0 server branch.
Tagged 10.0.4 head as v10.0.4

**Comment by mahalakshme** [comment]
#### on 24th October: https://github.com/avniproject/avni-webapp/issues/1364#issuecomment-2434714357

#### on 28th October: 
released [this](https://github.com/avniproject/avni-webapp/issues/1365) also as 10.0.4
10.0.4 merged to master and 10.1.0, 
update release notes, 
updated 10.0.4 tag
