### ISSUE TITLE
Ability for Organisation admin to logIn into mobile app

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#99]
Organisation admin should be able to login into mobile app.

**Comment by garimadosar5** [comment]
QA Notes - 
- Admin user can log in into the application but there is no catchment assigned to admin user so there is no data to check and the user cannot fill any new data because the location is not assigned.

**Comment by vindeolal** [comment]
Now we can add catchment to org_admin user from admin UI.
